# Generated by Django 6.0 on 2025-12-14 06:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('context_id', models.UUIDField()),
                ('thread_type', models.CharField(choices=[('DISCUSSION', 'Discussion'), ('CLARIFICATION', 'Clarification Request'), ('INTERNAL_NOTE', 'Internal Note'), ('RULING', 'Ruling/Decision')], default='DISCUSSION', max_length=50)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PENDING_RESPONSE', 'Pending Response'), ('CLOSED', 'Closed'), ('ESCALATED', 'Escalated')], default='OPEN', max_length=50)),
                ('initiated_by_role', models.CharField(help_text='Role of user at thread creation time', max_length=100)),
                ('sla_deadline', models.DateTimeField(blank=True, help_text='Deadline before auto-escalation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_threads', to=settings.AUTH_USER_MODEL)),
                ('context_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_threads', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='participated_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_role', models.CharField(help_text='Role of sender at message creation time', max_length=100)),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('STANDARD', 'Standard Message'), ('CLARIFICATION_REQUEST', 'Clarification Request'), ('CLARIFICATION_RESPONSE', 'Clarification Response'), ('RULING', 'Ruling/Decision'), ('INTERNAL', 'Internal Note')], default='STANDARD', max_length=50)),
                ('is_ruling', models.BooleanField(default=False, help_text='Marks this as an authoritative ruling')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('references', models.ForeignKey(blank=True, help_text='Reference to a previous message for corrections', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by', to='communications.message')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.thread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_role', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('THREAD_CREATED', 'Thread Created'), ('MESSAGE_SENT', 'Message Sent'), ('CLARIFICATION_REQUESTED', 'Clarification Requested'), ('CLARIFICATION_RESPONDED', 'Clarification Responded'), ('RULING_ISSUED', 'Ruling Issued'), ('THREAD_CLOSED', 'Thread Closed'), ('ESCALATION_TRIGGERED', 'Escalation Triggered'), ('THREAD_VIEWED', 'Thread Viewed')], max_length=50)),
                ('resource_type', models.CharField(help_text='Thread or Message', max_length=100)),
                ('resource_id', models.UUIDField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor'], name='communicati_actor_i_398553_idx'), models.Index(fields=['action'], name='communicati_action_560fa2_idx'), models.Index(fields=['resource_type', 'resource_id'], name='communicati_resourc_f24059_idx'), models.Index(fields=['timestamp'], name='communicati_timesta_5feba2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('NEW_MESSAGE', 'New Message'), ('CLARIFICATION_REQUESTED', 'Clarification Requested'), ('CLARIFICATION_RESPONDED', 'Clarification Responded'), ('RULING_ISSUED', 'Ruling Issued'), ('ESCALATION', 'Escalation Alert'), ('DEADLINE_BREACH', 'Deadline Breach'), ('THREAD_CLOSED', 'Thread Closed')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('context_id', models.UUIDField(blank=True, null=True)),
                ('deep_link', models.CharField(blank=True, help_text='Direct URL to the relevant page', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='communicati_recipie_dd2f99_idx'), models.Index(fields=['notification_type'], name='communicati_notific_8e3688_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['context_type', 'context_id'], name='communicati_context_e2a3e1_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['status'], name='communicati_status_bc6179_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['thread_type'], name='communicati_thread__cb516d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread'], name='communicati_thread__1d4701_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='communicati_sender__822f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type'], name='communicati_message_4a1d97_idx'),
        ),
    ]
