# Generated by Django 6.0 on 2025-12-23 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='chat_name',
            field=models.CharField(blank=True, help_text='Custom name for group chats', max_length=255),
        ),
        migrations.AlterField(
            model_name='thread',
            name='context_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='context_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_type',
            field=models.CharField(choices=[('DISCUSSION', 'Discussion'), ('CLARIFICATION', 'Clarification Request'), ('INTERNAL_NOTE', 'Internal Note'), ('RULING', 'Ruling/Decision'), ('DIRECT_MESSAGE', 'Direct Message'), ('GROUP_CHAT', 'Group Chat')], default='DISCUSSION', max_length=50),
        ),
    ]
