# Generated by Django 6.0 on 2025-12-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_alter_communicationauditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_encrypted',
            field=models.BooleanField(default=True, help_text='Whether content is encrypted'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(help_text='AES-256 encrypted message content'),
        ),
    ]
