# Generated by Django 6.0 on 2025-12-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_add_message_encryption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_encrypted',
            field=models.BooleanField(default=False, help_text='Whether content is encrypted'),
        ),
    ]
