# Generated by Django 6.0 on 2026-03-06 12:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0012_project_latest_site_photo'),
        ('scheduling', '0004_scheduletask_actual_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySiteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, help_text='Date of site execution (set automatically on creation)')),
                ('achieved_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Quantity of work executed on this day (in the task UOM)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('remarks', models.TextField(blank=True, default='', help_text='Site engineer remarks, observations, or notes')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude of site activity', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude of site activity', max_digits=9, null=True)),
                ('weather_temp_max', models.DecimalField(blank=True, decimal_places=2, help_text='Max temperature (°C) for the day. Auto-fetched from Open-Meteo.', max_digits=5, null=True)),
                ('weather_temp_min', models.DecimalField(blank=True, decimal_places=2, help_text='Min temperature (°C) for the day. Auto-fetched from Open-Meteo.', max_digits=5, null=True)),
                ('weather_rain_mm', models.DecimalField(blank=True, decimal_places=2, help_text='Total precipitation (mm) for the day. Auto-fetched from Open-Meteo.', max_digits=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who submitted this log', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_logs_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project this execution log belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='site_logs', to='projects.project')),
                ('task', models.ForeignKey(help_text='ScheduleTask this execution contributes progress to', on_delete=django.db.models.deletion.CASCADE, related_name='site_logs', to='scheduling.scheduletask')),
            ],
            options={
                'verbose_name': 'Daily Site Log',
                'verbose_name_plural': 'Daily Site Logs',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Uploaded site photograph', upload_to='execution/site_images/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False, help_text='If True, this image is synced to Project.latest_site_photo via signal')),
                ('caption', models.CharField(blank=True, default='', help_text='Optional caption for the image', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('site_log', models.ForeignKey(help_text='The site log this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='execution.dailysitelog')),
            ],
            options={
                'verbose_name': 'Site Image',
                'verbose_name_plural': 'Site Images',
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dailysitelog',
            index=models.Index(fields=['project', 'date'], name='execution_d_project_a3a764_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysitelog',
            index=models.Index(fields=['task', 'date'], name='execution_d_task_id_e0da8d_idx'),
        ),
    ]
