# Generated by Django 6.0 on 2025-12-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletask',
            name='external_id',
            field=models.CharField(blank=True, help_text='UID from P6/MSP/Excel', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Custom columns from imported files'),
        ),
    ]
