# Generated by Django 6.0 on 2026-01-10 18:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_earned_value_project_financial_progress_and_more'),
        ('scheduling', '0002_scheduletask_external_id_scheduletask_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduletask',
            options={'ordering': ['start_date', 'wbs_code', 'name']},
        ),
        migrations.RemoveField(
            model_name='scheduletask',
            name='progress',
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='actual_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Actual Cost of Work Performed (ACWP)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='budgeted_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Budgeted Cost of Work Scheduled (BCWS) for EV calculations', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='computed_progress',
            field=models.FloatField(default=0.0, help_text='System-calculated progress percentage (0-100). DO NOT EDIT DIRECTLY.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='executed_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Actual executed quantity', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='is_approval_granted',
            field=models.BooleanField(default=False, help_text='If True, progress can exceed the cap (up to 100%)'),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='is_critical',
            field=models.BooleanField(default=False, help_text='True if this task is on the critical path'),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='manual_progress_justification',
            field=models.TextField(blank=True, default='', help_text='Required justification when using manual progress'),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='manual_progress_value',
            field=models.FloatField(blank=True, help_text='Only used if progress_method is MANUAL', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='max_progress_without_approval',
            field=models.FloatField(default=70.0, help_text='Progress cap until milestone/approval is complete', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='parent_task',
            field=models.ForeignKey(blank=True, help_text='Parent task for WBS hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='scheduling.scheduletask'),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='planned_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Planned quantity for quantity-based progress', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='progress_method',
            field=models.CharField(choices=[('QUANTITY', 'Quantity-Based'), ('MILESTONE', 'Milestone-Based'), ('COST', 'Cost-Based'), ('TIME', 'Time-Based'), ('MANUAL', 'Manual (Restricted)')], default='QUANTITY', help_text='Method used to calculate task progress', max_length=20),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='uom',
            field=models.CharField(blank=True, default='', help_text='Unit of Measurement (e.g., m3, kg, nos)', max_length=50),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='wbs_code',
            field=models.CharField(blank=True, default='', help_text='Work Breakdown Structure code (e.g., 1.2.3)', max_length=50),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Weight for project-level aggregation. Null = unresolved.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='weight_source',
            field=models.CharField(choices=[('QUANTITY', 'Derived from Quantity'), ('COST', 'Derived from Cost'), ('MANUAL', 'Manually Assigned'), ('DURATION', 'Derived from Duration (Fallback)'), ('UNRESOLVED', 'Not Yet Resolved')], default='UNRESOLVED', help_text='How the weight was determined', max_length=20),
        ),
        migrations.AddIndex(
            model_name='scheduletask',
            index=models.Index(fields=['project', 'status'], name='scheduling__project_f5d919_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduletask',
            index=models.Index(fields=['project', 'is_milestone'], name='scheduling__project_8db4ab_idx'),
        ),
    ]
