# Generated by Django 6.0 on 2026-01-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_class',
            field=models.CharField(blank=True, choices=[('Class A', 'Class A (Unlimited)'), ('Class B', 'Class B (Up to ₹50 Cr)'), ('Class C', 'Class C (Up to ₹10 Cr)'), ('Class D', 'Class D (Up to ₹2 Cr)'), ('Class E', 'Class E (Up to ₹50 Lakh)')], help_text='Contractor registration class (only for EPC_Contractor role)', max_length=20, null=True),
        ),
    ]
