# Generated by Django 6.0 on 2025-12-23 14:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_thread_chat_name_alter_thread_context_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='communications/attachments/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('content_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReadReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message Read Receipt',
                'verbose_name_plural': 'Message Read Receipts',
                'ordering': ['-read_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_muted', models.BooleanField(default=False)),
                ('muted_until', models.DateTimeField(blank=True, help_text='Mute until this time (null = forever)', null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('pinned_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Thread Participant',
                'verbose_name_plural': 'Thread Participants',
                'ordering': ['-is_pinned', '-joined_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='communicationauditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Communication Audit Log', 'verbose_name_plural': 'Communication Audit Logs'},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-created_at'], 'verbose_name': 'Communication Thread', 'verbose_name_plural': 'Communication Threads'},
        ),
        migrations.RemoveIndex(
            model_name='communicationauditlog',
            name='communicati_actor_i_398553_idx',
        ),
        migrations.RemoveIndex(
            model_name='communicationauditlog',
            name='communicati_action_560fa2_idx',
        ),
        migrations.RemoveIndex(
            model_name='communicationauditlog',
            name='communicati_resourc_f24059_idx',
        ),
        migrations.RemoveIndex(
            model_name='communicationauditlog',
            name='communicati_timesta_5feba2_idx',
        ),
        migrations.AddField(
            model_name='thread',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='communicationauditlog',
            name='action',
            field=models.CharField(choices=[('THREAD_CREATED', 'Thread Created'), ('MESSAGE_SENT', 'Message Sent'), ('THREAD_CLOSED', 'Thread Closed'), ('THREAD_ESCALATED', 'Thread Escalated'), ('PARTICIPANT_ADDED', 'Participant Added'), ('PARTICIPANT_REMOVED', 'Participant Removed'), ('NOTIFICATION_SENT', 'Notification Sent')], max_length=100),
        ),
        migrations.AlterField(
            model_name='communicationauditlog',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communicationauditlog',
            name='actor_role',
            field=models.CharField(help_text='Role at time of action', max_length=100),
        ),
        migrations.AlterField(
            model_name='communicationauditlog',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='Additional context about the action'),
        ),
        migrations.AlterField(
            model_name='communicationauditlog',
            name='resource_id',
            field=models.UUIDField(help_text='ID of the affected resource'),
        ),
        migrations.AlterField(
            model_name='communicationauditlog',
            name='resource_type',
            field=models.CharField(help_text='Type of resource (Thread, Message, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_ruling',
            field=models.BooleanField(default=False, help_text='Official ruling flag for govt oversight'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('STANDARD', 'Standard Message'), ('CLARIFICATION_REQUEST', 'Clarification Request'), ('CLARIFICATION_RESPONSE', 'Clarification Response'), ('RULING', 'Official Ruling')], default='STANDARD', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='references',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='communications.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_MESSAGE', 'New Message'), ('THREAD_ASSIGNED', 'Thread Assigned'), ('RULING_ISSUED', 'Ruling Issued'), ('CLARIFICATION_REQUESTED', 'Clarification Requested'), ('SLA_APPROACHING', 'SLA Deadline Approaching'), ('THREAD_ESCALATED', 'Thread Escalated')], max_length=50),
        ),
        migrations.AddField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communications.message'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagereadreceipt',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='communications.message'),
        ),
        migrations.AddField(
            model_name='messagereadreceipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threadparticipant',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_participants', to='communications.thread'),
        ),
        migrations.AddField(
            model_name='threadparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='communicationauditlog',
            name='user_agent',
        ),
        migrations.AlterUniqueTogether(
            name='messagereadreceipt',
            unique_together={('message', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='threadparticipant',
            unique_together={('thread', 'user')},
        ),
    ]
