# Generated by Django 6.0 on 2025-12-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_attachment_messagereadreceipt_threadparticipant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationauditlog',
            name='action',
            field=models.CharField(choices=[('THREAD_CREATED', 'Thread Created'), ('MESSAGE_SENT', 'Message Sent'), ('THREAD_CLOSED', 'Thread Closed'), ('THREAD_ESCALATED', 'Thread Escalated'), ('PARTICIPANT_ADDED', 'Participant Added'), ('PARTICIPANT_REMOVED', 'Participant Removed'), ('NOTIFICATION_SENT', 'Notification Sent'), ('CLARIFICATION_REQUESTED', 'Clarification Requested'), ('CLARIFICATION_RESPONDED', 'Clarification Responded'), ('RULING_ISSUED', 'Ruling Issued'), ('ESCALATION_TRIGGERED', 'Escalation Triggered')], max_length=100),
        ),
    ]
