# Generated by Django 6.0 on 2026-01-01 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('projects', '0002_workpackage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='circle',
            field=models.ForeignKey(blank=True, help_text='Administrative circle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='masters.circle'),
        ),
        migrations.AddField(
            model_name='project',
            name='district',
            field=models.ForeignKey(blank=True, help_text='Project district', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='masters.district'),
        ),
        migrations.AddField(
            model_name='project',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Administrative division', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='masters.division'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_category',
            field=models.ForeignKey(blank=True, help_text='Project category classification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='masters.projectcategory'),
        ),
        migrations.AddField(
            model_name='project',
            name='scheme',
            field=models.ForeignKey(blank=True, help_text='Specific scheme', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='masters.scheme'),
        ),
        migrations.AddField(
            model_name='project',
            name='scheme_type',
            field=models.ForeignKey(blank=True, help_text='Type of scheme', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='masters.schemetype'),
        ),
        migrations.AddField(
            model_name='project',
            name='sub_division',
            field=models.ForeignKey(blank=True, help_text='Administrative sub-division', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='masters.subdivision'),
        ),
        migrations.AddField(
            model_name='project',
            name='town',
            field=models.ForeignKey(blank=True, help_text='Project town/city', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='masters.town'),
        ),
        migrations.AddField(
            model_name='project',
            name='work_type',
            field=models.ForeignKey(blank=True, help_text='Type of work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='masters.worktype'),
        ),
        migrations.AddField(
            model_name='project',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Administrative zone', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='masters.zone'),
        ),
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.CharField(blank=True, help_text='Physical address or landmark', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, help_text='Legacy category field', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='lat',
            field=models.FloatField(blank=True, help_text='Latitude for map display', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='lng',
            field=models.FloatField(blank=True, help_text='Longitude for map display', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
