# Generated by Django 6.0 on 2026-01-11 17:40
# HOTFIX: Fix corrupted migration state on production

from django.db import migrations


def check_and_fix_schema(apps, schema_editor):
    """
    Check the current database state and fix if needed.
    This handles the case where migration 0005 was partially applied
    or applied with a different version.
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check what columns exist in projects_project table
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'projects_project'
            AND column_name IN ('manager', 'manager_id', 'manager_legacy')
        """)
        existing_columns = [row[0] for row in cursor.fetchall()]
        
        print(f"Existing columns: {existing_columns}")
        
        # Case 1: Has manager (CharField) but not manager_legacy or manager_id
        # This means migration 0005 never ran - we need to fix this
        if 'manager' in existing_columns and 'manager_legacy' not in existing_columns:
            print("Found old 'manager' CharField - renaming to manager_legacy")
            cursor.execute('ALTER TABLE projects_project RENAME COLUMN manager TO manager_legacy')
            
        # Case 2: Has manager_id but not manager_legacy
        # This means the old broken migration ran and converted manager to FK directly
        if 'manager_id' in existing_columns and 'manager_legacy' not in existing_columns:
            print("Found manager_id but no manager_legacy - adding manager_legacy column")
            cursor.execute('ALTER TABLE projects_project ADD COLUMN IF NOT EXISTS manager_legacy VARCHAR(255) NULL')
            
        # Case 3: Has neither manager nor manager_id - need to add manager FK
        if 'manager_id' not in existing_columns:
            print("No manager_id found - adding manager FK column")
            cursor.execute('ALTER TABLE projects_project ADD COLUMN IF NOT EXISTS manager_id BIGINT NULL')
            # Add foreign key constraint
            cursor.execute("""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.table_constraints 
                        WHERE constraint_name = 'projects_project_manager_id_fk'
                    ) THEN
                        ALTER TABLE projects_project 
                        ADD CONSTRAINT projects_project_manager_id_fk 
                        FOREIGN KEY (manager_id) REFERENCES users_user(id) ON DELETE SET NULL;
                    END IF;
                END $$;
            """)


def reverse_schema_fix(apps, schema_editor):
    """Reverse is not supported - this is a one-way fix."""
    pass


class Migration(migrations.Migration):
    """
    Emergency schema fix for production database.
    Ensures the projects_project table has the correct columns:
    - manager_legacy (VARCHAR, nullable) - old CharField data
    - manager_id (BIGINT, nullable) - new ForeignKey to users_user
    """

    dependencies = [
        ('projects', '0005_add_approval_and_manager_fk'),
    ]

    operations = [
        migrations.RunPython(check_and_fix_schema, reverse_schema_fix),
    ]
