# Generated by Django 6.0 on 2025-12-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Under Review', 'Under Review')], default='Planning', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('progress', models.FloatField(default=0.0)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('manager', models.CharField(blank=True, max_length=255)),
                ('stakeholders', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('land_acquisition_status', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
