# Generated by Django 6.0 on 2026-01-10 18:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_master_foreignkeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='earned_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Computed Earned Value (EV). DO NOT EDIT DIRECTLY.', max_digits=15),
        ),
        migrations.AddField(
            model_name='project',
            name='financial_progress',
            field=models.FloatField(default=0.0, help_text='Computed financial progress (EV/Budget %). DO NOT EDIT DIRECTLY.', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='project',
            name='physical_progress',
            field=models.FloatField(default=0.0, help_text='Computed physical progress (0-100%). DO NOT EDIT DIRECTLY.', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='project',
            name='progress_state',
            field=models.CharField(choices=[('CLAIMED', 'Claimed'), ('VERIFIED', 'Verified'), ('FLAGGED', 'Flagged')], default='CLAIMED', help_text='Verification state of progress values', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='schedule_variance',
            field=models.FloatField(default=0.0, help_text='Schedule variance percentage. Negative = behind schedule.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.FloatField(default=0.0, help_text='DEPRECATED: Use physical_progress instead. Kept for backward compatibility.'),
        ),
    ]
