# Generated by Django 6.0 on 2026-01-11 07:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_earned_value_project_financial_progress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admin_approval_date',
            field=models.DateField(blank=True, help_text='Date of administrative approval', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='admin_approval_document',
            field=models.FileField(blank=True, help_text='Uploaded approval document (PDF/Image)', null=True, upload_to='projects/approvals/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='project',
            name='admin_approval_reference_no',
            field=models.CharField(blank=True, help_text='Administrative approval reference number', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='manager_legacy',
            field=models.CharField(blank=True, help_text='Old manager field - will be migrated', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Project Manager assigned to this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(help_text='Funding source name/type', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('document', models.FileField(blank=True, help_text='Supporting document for this funding source', null=True, upload_to='projects/funding_docs/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
