# Generated by Django 6.0 on 2026-01-12 13:25

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0002_add_notingsheet'),
        ('projects', '0006_fix_manager_schema'),
        ('scheduling', '0003_alter_scheduletask_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_code', models.CharField(blank=True, help_text='Auto-generated: RSK-{PROJECT_CODE}-{SEQ}', max_length=30, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('TECHNICAL', 'Technical'), ('FINANCIAL', 'Financial'), ('CONTRACTUAL', 'Contractual'), ('ENVIRONMENTAL', 'Environmental'), ('SAFETY', 'Safety'), ('POLITICAL', 'Political'), ('LEGAL', 'Legal'), ('OPERATIONAL', 'Operational'), ('SCHEDULE', 'Schedule/Timeline'), ('RESOURCE', 'Resource/Manpower'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('risk_source', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], default='INTERNAL', max_length=10)),
                ('probability', models.IntegerField(choices=[(1, 'Very Low (Rare)'), (2, 'Low (Unlikely)'), (3, 'Medium (Possible)'), (4, 'High (Likely)'), (5, 'Very High (Almost Certain)')], default=3, help_text='Likelihood of risk occurring (1-5)')),
                ('impact', models.IntegerField(choices=[(1, 'Negligible'), (2, 'Minor'), (3, 'Moderate'), (4, 'Major'), (5, 'Critical')], default=3, help_text='Severity if risk occurs (1-5)')),
                ('risk_score', models.IntegerField(default=9, editable=False, help_text='Auto-calculated: probability × impact (1-25)')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', editable=False, help_text='Auto-calculated from risk score', max_length=10)),
                ('status', models.CharField(choices=[('IDENTIFIED', 'Identified'), ('ASSESSED', 'Assessed'), ('MITIGATING', 'Mitigating'), ('MITIGATED', 'Mitigated'), ('CLOSED', 'Closed'), ('OCCURRED', 'Occurred'), ('ACCEPTED', 'Accepted')], default='IDENTIFIED', max_length=15)),
                ('identified_date', models.DateField(auto_now_add=True)),
                ('target_resolution', models.DateField(blank=True, help_text='Expected date to resolve/mitigate risk', null=True)),
                ('actual_closure', models.DateField(blank=True, help_text='Date when risk was closed', null=True)),
                ('review_date', models.DateField(blank=True, help_text='Next scheduled review date', null=True)),
                ('response_strategy', models.CharField(blank=True, choices=[('AVOID', 'Avoid'), ('MITIGATE', 'Mitigate'), ('TRANSFER', 'Transfer'), ('ACCEPT', 'Accept'), ('ESCALATE', 'Escalate')], max_length=10, null=True)),
                ('mitigation_plan', models.TextField(blank=True, help_text='Detailed plan to reduce probability/impact')),
                ('contingency_plan', models.TextField(blank=True, help_text='Actions if risk materializes')),
                ('cost_impact', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated financial impact in INR', max_digits=15)),
                ('schedule_impact_days', models.IntegerField(default=0, help_text='Estimated schedule delay in days')),
                ('residual_risk_score', models.IntegerField(blank=True, help_text='Risk score after mitigation applied', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_risks', to=settings.AUTH_USER_MODEL)),
                ('edms_folder', models.ForeignKey(blank=True, help_text='Auto-created folder: {Project}/Risk Management/{risk_code}', null=True, on_delete=django.db.models.deletion.SET_NULL, to='edms.folder')),
                ('owner', models.ForeignKey(blank=True, help_text='Person responsible for managing this risk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='projects.project')),
                ('schedule_task', models.ForeignKey(blank=True, help_text='Linked schedule task affected by this risk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='scheduling.scheduletask')),
                ('work_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='projects.workpackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Risk Created'), ('UPDATED', 'Risk Updated'), ('STATUS_CHANGED', 'Status Changed'), ('DOCUMENT_ADDED', 'Document Added'), ('MITIGATION_ADDED', 'Mitigation Action Added'), ('MITIGATION_SUBMITTED', 'Mitigation Submitted'), ('MITIGATION_APPROVED', 'Mitigation Approved'), ('MITIGATION_REJECTED', 'Mitigation Rejected'), ('OWNER_CHANGED', 'Owner Changed'), ('ASSESSMENT_UPDATED', 'Risk Assessment Updated'), ('CLOSED', 'Risk Closed')], max_length=25)),
                ('actor_name', models.CharField(blank=True, max_length=200)),
                ('actor_role', models.CharField(blank=True, max_length=50)),
                ('details', models.JSONField(default=dict, help_text='Additional action details')),
                ('previous_values', models.JSONField(blank=True, default=dict, help_text='Field values before change')),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='Field values after change')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='projects.risk')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RiskDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('EVIDENCE', 'Evidence/Proof'), ('ASSESSMENT', 'Risk Assessment Report'), ('MITIGATION_PLAN', 'Mitigation Plan'), ('MITIGATION_PROOF', 'Mitigation Action Proof'), ('CLOSURE_REPORT', 'Closure Report'), ('INSURANCE', 'Insurance Claim'), ('MEETING_NOTES', 'Meeting Notes'), ('CORRESPONDENCE', 'Correspondence'), ('INCIDENT_REPORT', 'Incident Report'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional context for this document')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_attachments', to='edms.document')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_documents', to='projects.risk')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskMitigationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_number', models.PositiveIntegerField(help_text='Auto-incremented per risk')),
                ('action_type', models.CharField(choices=[('PREVENTIVE', 'Preventive Action'), ('CORRECTIVE', 'Corrective Action'), ('DETECTIVE', 'Detective Control'), ('CONTINGENCY', 'Contingency Measure'), ('TRANSFER', 'Risk Transfer (Insurance/Contract)'), ('ACCEPTANCE', 'Risk Acceptance with Justification')], default='CORRECTIVE', max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('action_date', models.DateField(help_text='Date when action was taken')),
                ('target_completion', models.DateField(blank=True, help_text='Target date for action completion', null=True)),
                ('actual_completion', models.DateField(blank=True, help_text='Actual completion date', null=True)),
                ('effectiveness_rating', models.IntegerField(blank=True, help_text='1=Not Effective, 3=Moderate, 5=Highly Effective', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('residual_probability', models.IntegerField(blank=True, choices=[(1, 'Very Low (Rare)'), (2, 'Low (Unlikely)'), (3, 'Medium (Possible)'), (4, 'High (Likely)'), (5, 'Very High (Almost Certain)')], help_text='Probability after this action', null=True)),
                ('residual_impact', models.IntegerField(blank=True, choices=[(1, 'Negligible'), (2, 'Minor'), (3, 'Moderate'), (4, 'Major'), (5, 'Critical')], help_text='Impact after this action', null=True)),
                ('cost_incurred', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost incurred for this mitigation action', max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mitigations', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_mitigations', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_actions', to='projects.risk')),
            ],
            options={
                'ordering': ['-action_number'],
            },
        ),
        migrations.CreateModel(
            name='MitigationProofDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, help_text='Brief description of what this document proves')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_proofs', to='edms.document')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mitigation_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_documents', to='projects.riskmitigationaction')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['project', 'status'], name='projects_ri_project_1387bb_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['severity', 'status'], name='projects_ri_severit_e26530_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['owner', 'status'], name='projects_ri_owner_i_78be84_idx'),
        ),
        migrations.AddIndex(
            model_name='riskauditlog',
            index=models.Index(fields=['risk', 'action'], name='projects_ri_risk_id_0b7757_idx'),
        ),
        migrations.AddIndex(
            model_name='riskauditlog',
            index=models.Index(fields=['timestamp'], name='projects_ri_timesta_8edb9a_idx'),
        ),
        migrations.AddIndex(
            model_name='riskmitigationaction',
            index=models.Index(fields=['risk', 'status'], name='projects_ri_risk_id_b84aec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='riskmitigationaction',
            unique_together={('risk', 'action_number')},
        ),
    ]
