# Generated by Django 6.0 on 2026-01-23 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0002_add_notingsheet'),
        ('masters', '0006_add_location_district'),
        ('projects', '0007_add_risk_management_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpackage',
            name='agreement_document',
            field=models.FileField(blank=True, help_text='Temporary storage during upload, moved to EDMS after creation', null=True, upload_to='temp/package_agreements/'),
        ),
        migrations.AddField(
            model_name='workpackage',
            name='agreement_document_edms',
            field=models.ForeignKey(blank=True, help_text='EDMS document reference for agreement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_agreements', to='edms.document'),
        ),
        migrations.AddField(
            model_name='workpackage',
            name='contractor_master',
            field=models.ForeignKey(blank=True, help_text='Contractor assigned to this package (new field)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_packages', to='masters.contractor'),
        ),
        migrations.AddField(
            model_name='workpackage',
            name='package_folder_edms',
            field=models.ForeignKey(blank=True, help_text="EDMS folder for this package's documents", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_packages', to='edms.folder'),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='agreement_no',
            field=models.CharField(blank=True, help_text='Agreement/Contract number', max_length=100, null=True),
        ),
    ]
