# Generated by Django 6.0 on 2026-01-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_add_edms_fields_to_workpackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workpackage',
            name='agreement_document_edms',
        ),
        migrations.RemoveField(
            model_name='workpackage',
            name='package_folder_edms',
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='agreement_document',
            field=models.FileField(blank=True, help_text='Agreement document upload', null=True, upload_to='temp/package_agreements/'),
        ),
    ]
