# Generated by Django 6.0.1 on 2026-01-23 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_add_location_district'),
        ('projects', '0008_add_edms_fields_to_workpackage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Planning', 'Planning'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Under Review', 'Under Review')], db_index=True, default='Planning', max_length=50),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'physical_progress'], name='proj_status_progress_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['start_date', 'end_date'], name='proj_date_range_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-created_at', 'status'], name='proj_created_status_idx'),
        ),
    ]
