# Generated by Django 6.0.1 on 2026-01-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_add_performance_indexes'),
        ('projects', '0009_remove_workpackage_agreement_document_edms_and_more'),
    ]

    operations = [
    ]
