# Generated by Django 6.0 on 2026-02-24 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_merge_20260127_2329'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workpackage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='baseline_frozen_by',
            field=models.ForeignKey(blank=True, help_text='User who froze the baseline', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frozen_baselines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='baseline_frozen_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the baseline was frozen', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_baseline_frozen',
            field=models.BooleanField(default=False, help_text='Whether the baseline schedule is frozen (immutable)'),
        ),
    ]
