# Generated by Django 6.0 on 2026-03-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_workpackage_options_project_baseline_frozen_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='latest_site_photo',
            field=models.ImageField(blank=True, help_text='Automatically updated by execution.signals when a SiteImage with is_primary=True is saved for any DailySiteLog of this project.', null=True, upload_to='projects/site_photos/'),
        ),
    ]
