# Generated by Django 6.0 on 2025-12-25 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_source_name_fundhead_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetlineitem',
            name='fund_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.fundhead'),
        ),
    ]
