# Generated by Django 6.0 on 2026-01-02 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='hod_user',
            field=models.ForeignKey(blank=True, help_text='User account of the Head of Division', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_divisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='reporting_officer_user',
            field=models.ForeignKey(blank=True, help_text='User account of the Sub-Divisional Engineer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_subdivisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zone',
            name='head_user',
            field=models.ForeignKey(blank=True, help_text='User account of the Zonal Head', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_zones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='division',
            name='hod',
            field=models.CharField(blank=True, help_text='[Deprecated] Head of Division name', max_length=255),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='reporting_officer',
            field=models.CharField(blank=True, help_text='[Deprecated] Sub-Divisional Engineer name', max_length=255),
        ),
        migrations.AlterField(
            model_name='zone',
            name='head',
            field=models.CharField(blank=True, help_text='[Deprecated] Zonal Head name and designation', max_length=255),
        ),
    ]
