# Generated by Django 6.0 on 2026-01-02 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_add_user_links_to_hierarchy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='linked_user',
            field=models.OneToOneField(blank=True, help_text='Linked user account for self-registered contractors', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
