# Generated by Django 6.0.1 on 2026-01-10 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_country_state_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['district', 'name'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(help_text='City/Town/Area name', max_length=100),
        ),
        migrations.CreateModel(
            name='LocationDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='District name', max_length=100)),
                ('code', models.CharField(blank=True, help_text='District code if applicable', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this district is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(help_text='Parent state', on_delete=django.db.models.deletion.CASCADE, related_name='location_districts', to='masters.state')),
            ],
            options={
                'verbose_name': 'Location District',
                'verbose_name_plural': 'Location Districts',
                'db_table': 'masters_location_districts',
                'ordering': ['state', 'name'],
                'unique_together': {('state', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.ForeignKey(default=1, help_text='Parent district', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='masters.locationdistrict'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('district', 'name')},
        ),
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
    ]
