# Generated by Django 6.0 on 2025-12-13 14:53

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('VIEW', 'Viewed'), ('DOWNLOAD', 'Downloaded'), ('UPLOAD', 'Uploaded'), ('STATUS_CHANGE', 'Changed Status'), ('DELETE', 'Deleted')], max_length=50)),
                ('resource_id', models.CharField(help_text='ID of the Document or resource', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_id', models.CharField(blank=True, help_text='Reference to Work Package ID', max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(help_text='e.g., Drawing, Invoice, Report', max_length=100)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('CLARIFICATION_REQ', 'Clarification Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=50)),
                ('s3_key', models.CharField(help_text='Path in Object Store', max_length=1024)),
                ('file_hash', models.CharField(db_index=True, help_text='SHA-256 Checksum', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dynamic fields like Drawing No, Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('s3_key', models.CharField(max_length=1024)),
                ('file_hash', models.CharField(max_length=64)),
                ('change_remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='edms.document')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='NotingSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(help_text='Role of the user at the time of noting', max_length=100)),
                ('remark_text', models.TextField()),
                ('is_ruling', models.BooleanField(default=False, help_text='Did this remark change the document status?')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notings', to='edms.document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='edms_metadata_gin'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='edms_docume_status_2a3a45_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['project'], name='edms_docume_project_69a4d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
    ]
