# Generated by Django 6.0 on 2025-12-14 07:16

import django.db.models.deletion
import edms.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('DRAWING', 'Drawing'), ('REPORT', 'Report'), ('CONTRACT', 'Contract'), ('CORRESPONDENCE', 'Correspondence'), ('SPECIFICATION', 'Specification'), ('INVOICE', 'Invoice'), ('MEDIA', 'Media'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('document_number', models.CharField(blank=True, help_text='Official document reference number', max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('REVISION_REQUESTED', 'Revision Requested'), ('VALIDATED', 'Validated'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('is_confidential', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible additional attributes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('IN_PROGRESS', 'In Progress'), ('VALIDATED', 'Validated (Awaiting Final)'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_workflows', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='edms.document')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to=edms.models.document_file_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='Size in bytes')),
                ('file_hash', models.CharField(help_text='SHA-256 hash for integrity', max_length=64)),
                ('mime_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_notes', models.TextField(blank=True, help_text='What changed in this version')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='edms.document')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_document', to='edms.documentversion'),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='edms.folder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'parent', 'project')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='edms.folder'),
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_type', models.CharField(choices=[('PMNC_REVIEW', 'PMNC Review'), ('SPV_APPROVAL', 'SPV Final Approval')], max_length=20)),
                ('step_order', models.PositiveIntegerField()),
                ('role_required', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested')], default='PENDING', max_length=20)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='edms.approvalworkflow')),
            ],
            options={
                'ordering': ['step_order'],
                'unique_together': {('workflow', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='DocumentAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_role', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('UPLOAD', 'Document Uploaded'), ('VERSION_CREATED', 'New Version Created'), ('VIEW', 'Document Viewed'), ('DOWNLOAD', 'Document Downloaded'), ('MOVED', 'Document Moved'), ('STATUS_CHANGED', 'Status Changed'), ('SUBMITTED_FOR_REVIEW', 'Submitted for Review'), ('VALIDATED', 'Validated by PMNC'), ('APPROVED', 'Final Approval'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested'), ('ARCHIVED', 'Archived'), ('FOLDER_CREATED', 'Folder Created'), ('FOLDER_MOVED', 'Folder Moved')], max_length=30)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.UUIDField()),
                ('details', models.JSONField(default=dict, help_text='Additional context about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edms_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='edms_docume_resourc_815757_idx'), models.Index(fields=['actor', 'action'], name='edms_docume_actor_i_63b406_idx'), models.Index(fields=['timestamp'], name='edms_docume_timesta_e1a5a2_idx')],
            },
        ),
    ]
