# Generated by Django 6.0 on 2025-12-14 10:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotingSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_number', models.PositiveIntegerField(help_text='Sequential number within document')),
                ('note_type', models.CharField(choices=[('REMARK', 'Remark/Observation'), ('CLARIFICATION_REQUEST', 'Clarification Request'), ('CLARIFICATION_RESPONSE', 'Clarification Response'), ('RECOMMENDATION', 'Recommendation'), ('RULING', 'Decision/Ruling')], default='REMARK', max_length=30)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('page_reference', models.JSONField(blank=True, help_text="Page and coordinate reference: {'page': 3, 'coords': [x,y]}", null=True)),
                ('ruling_action', models.CharField(choices=[('NONE', 'None'), ('VALIDATE', 'Validate Document'), ('APPROVE', 'Approve Document'), ('REJECT', 'Reject Document'), ('REQUEST_REVISION', 'Request Revision')], default='NONE', help_text='Action to take when ruling is submitted', max_length=30)),
                ('author_name', models.CharField(help_text='Frozen author name', max_length=200)),
                ('author_role', models.CharField(help_text='Frozen author role', max_length=50)),
                ('author_designation', models.CharField(blank=True, help_text='Official designation', max_length=200)),
                ('is_draft', models.BooleanField(default=True, help_text='Draft notes are editable, submitted notes are immutable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Timestamp when note was finalized', null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noting_entries', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notings', to='edms.document')),
                ('document_version', models.ForeignKey(blank=True, help_text='Specific version this note references', null=True, on_delete=django.db.models.deletion.SET_NULL, to='edms.documentversion')),
                ('references_note', models.ForeignKey(blank=True, help_text='Reference to a previous note being corrected or responded to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by', to='edms.notingsheet')),
                ('workflow', models.ForeignKey(blank=True, help_text='Linked approval workflow', null=True, on_delete=django.db.models.deletion.SET_NULL, to='edms.approvalworkflow')),
            ],
            options={
                'ordering': ['note_number'],
                'indexes': [models.Index(fields=['document', 'is_draft'], name='edms_noting_documen_2fd5d6_idx'), models.Index(fields=['author', 'created_at'], name='edms_noting_author__3d4fe0_idx')],
                'unique_together': {('document', 'note_number')},
            },
        ),
    ]
