# Generated by Django 6.0 on 2025-12-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('ifsc_code', models.CharField(db_index=True, help_text='11-character IFSC code (Format: ABCD0123456)', max_length=11, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(db_index=True, help_text='Full name of the bank', max_length=255)),
                ('branch_name', models.CharField(help_text='Branch name', max_length=255)),
                ('address', models.TextField(blank=True, help_text='Complete branch address')),
                ('city', models.CharField(blank=True, db_index=True, help_text='City name', max_length=100)),
                ('district', models.CharField(blank=True, help_text='District name', max_length=100)),
                ('state', models.CharField(blank=True, db_index=True, help_text='State name', max_length=100)),
                ('contact', models.CharField(blank=True, help_text='Branch contact number', max_length=50)),
                ('rtgs', models.BooleanField(default=True, help_text='RTGS enabled')),
                ('neft', models.BooleanField(default=True, help_text='NEFT enabled')),
                ('imps', models.BooleanField(default=True, help_text='IMPS enabled')),
                ('upi', models.BooleanField(default=False, help_text='UPI enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.CharField(default='NPCI/RBI via Razorpay', help_text='Source of the data', max_length=100)),
                ('last_verified', models.DateField(blank=True, help_text='Last date data was verified', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this branch is currently active')),
            ],
            options={
                'verbose_name': 'Bank Branch (IFSC)',
                'verbose_name_plural': 'Bank Branches (IFSC)',
                'db_table': 'banks_ifsc',
                'ordering': ['bank_name', 'branch_name'],
                'indexes': [models.Index(fields=['bank_name'], name='banks_ifsc_bank_na_995707_idx'), models.Index(fields=['city'], name='banks_ifsc_city_d8ea99_idx'), models.Index(fields=['state'], name='banks_ifsc_state_dbdd8b_idx'), models.Index(fields=['is_active'], name='banks_ifsc_is_acti_2b8b0d_idx')],
            },
        ),
    ]
