# Generated by Django 6.0 on 2026-01-01 10:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='e.g., C-CIVIL', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full name of the Circle', max_length=255)),
                ('authority_level', models.CharField(choices=[('CE', 'Chief Engineer'), ('SE', 'Superintending Engineer')], default='SE', help_text='Rank of officer heading the Circle', max_length=5)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Circle',
                'verbose_name_plural': 'Circles',
                'db_table': 'masters_circle',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='e.g., C-10025', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full legal name of contractor/firm', max_length=500)),
                ('contractor_type', models.CharField(choices=[('Proprietorship', 'Proprietorship'), ('Partnership', 'Partnership'), ('Private Limited', 'Private Limited'), ('Public Limited', 'Public Limited'), ('LLP', 'Limited Liability Partnership'), ('Government', 'Government Entity'), ('Other', 'Other')], default='Proprietorship', max_length=50)),
                ('registration_class', models.CharField(blank=True, choices=[('Class A', 'Class A (Unlimited)'), ('Class B', 'Class B (Up to ₹50 Cr)'), ('Class C', 'Class C (Up to ₹10 Cr)'), ('Class D', 'Class D (Up to ₹2 Cr)'), ('Class E', 'Class E (Up to ₹50 Lakh)')], max_length=20)),
                ('registration_number', models.CharField(blank=True, help_text='Official registration/license number', max_length=100)),
                ('pan', models.CharField(blank=True, help_text='10-digit PAN', max_length=10)),
                ('gstin', models.CharField(blank=True, help_text='15-digit GSTIN', max_length=15)),
                ('tds_rate', models.DecimalField(decimal_places=2, default=2.0, help_text='TDS percentage', max_digits=5)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True, help_text='Registered address')),
                ('blacklisted', models.BooleanField(default=False, help_text='Barred from bidding')),
                ('blacklist_reason', models.TextField(blank=True)),
                ('validity_date', models.DateField(blank=True, help_text='Registration validity', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contractor',
                'verbose_name_plural': 'Contractors',
                'db_table': 'masters_contractor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='e.g., D-410', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Official district name', max_length=255)),
                ('state_name', models.CharField(help_text='State the district belongs to', max_length=100)),
                ('pincode_range', models.CharField(blank=True, help_text='e.g., 560001 to 560099', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'db_table': 'masters_district',
                'ordering': ['state_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ETPMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='e.g., LABOUR-CESS', max_length=30, unique=True)),
                ('name', models.CharField(help_text='e.g., Labour Welfare Cess', max_length=255)),
                ('charge_type', models.CharField(choices=[('Deduction', 'Deduction'), ('Recovery', 'Recovery'), ('Levy', 'Levy'), ('Addition', 'Addition')], default='Deduction', max_length=20)),
                ('rate_percentage', models.DecimalField(decimal_places=3, default=0, help_text='e.g., 1.000 for 1%', max_digits=6)),
                ('basis_of_calculation', models.CharField(choices=[('Gross Bill Value', 'Gross Bill Value'), ('Works Component Only', 'Works Component Only'), ('Material Cost', 'Material Cost'), ('Labour Cost', 'Labour Cost'), ('Net Payable', 'Net Payable')], default='Gross Bill Value', help_text='Which amount to apply the percentage on', max_length=50)),
                ('effective_date', models.DateField(help_text='Date from which rate is applicable')),
                ('govt_reference', models.CharField(blank=True, help_text='Circular/order number', max_length=255)),
                ('account_head', models.CharField(blank=True, help_text='Internal finance ledger code', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ETP Charge',
                'verbose_name_plural': 'ETP Charges',
                'db_table': 'masters_etp',
                'ordering': ['charge_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='e.g., PC-MAJ', max_length=20, unique=True)),
                ('name', models.CharField(help_text='e.g., Major Project', max_length=255)),
                ('threshold_value', models.DecimalField(decimal_places=2, default=0, help_text='Minimum contract value in INR', max_digits=15)),
                ('approval_authority', models.CharField(blank=True, help_text='e.g., Chief Engineer/Cabinet', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
                'db_table': 'masters_project_category',
                'ordering': ['threshold_value'],
            },
        ),
        migrations.CreateModel(
            name='SchemeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='e.g., ST-CS', max_length=20, unique=True)),
                ('name', models.CharField(help_text='e.g., Centrally Sponsored', max_length=255)),
                ('category', models.CharField(choices=[('Infrastructure', 'Infrastructure'), ('Social Sector', 'Social Sector'), ('Education', 'Education'), ('Health', 'Health'), ('Agriculture', 'Agriculture'), ('Other', 'Other')], default='Infrastructure', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scheme Type',
                'verbose_name_plural': 'Scheme Types',
                'db_table': 'masters_scheme_type',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='e.g., WT-ROAD', max_length=20, unique=True)),
                ('name', models.CharField(help_text='e.g., New Road Construction', max_length=255)),
                ('sector', models.CharField(choices=[('PWD', 'Public Works Department'), ('Irrigation', 'Irrigation'), ('Health', 'Health'), ('Education', 'Education'), ('Roads', 'Roads & Highways'), ('Water Supply', 'Water Supply'), ('Other', 'Other')], default='PWD', max_length=50)),
                ('unit_of_measurement', models.CharField(blank=True, help_text='Km/Sq.m/Meters', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Work Type',
                'verbose_name_plural': 'Work Types',
                'db_table': 'masters_work_type',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='e.g., ZN-SOUTH', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full name of the Zone', max_length=255)),
                ('state_covered', models.CharField(blank=True, help_text='State or region managed', max_length=255)),
                ('head', models.CharField(blank=True, help_text='Zonal Head name and designation', max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'db_table': 'masters_zone',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ContractorBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(help_text='Bank account number', max_length=30)),
                ('account_type', models.CharField(choices=[('Current', 'Current Account'), ('Savings', 'Savings Account')], default='Current', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary account for payments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contractor_accounts', to='banks.bankbranch')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account_details', to='masters.contractor')),
            ],
            options={
                'verbose_name': 'Contractor Bank Account',
                'verbose_name_plural': 'Contractor Bank Accounts',
                'db_table': 'masters_contractor_bank_account',
                'unique_together': {('contractor', 'account_number')},
            },
        ),
        migrations.AddField(
            model_name='contractor',
            name='bank_accounts',
            field=models.ManyToManyField(blank=True, related_name='contractors', through='masters.ContractorBankAccount', to='banks.bankbranch'),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='e.g., DIV-NGR', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full name of the Division', max_length=255)),
                ('hod', models.CharField(blank=True, help_text='Head of Division name', max_length=255)),
                ('contact_email', models.EmailField(blank=True, help_text='Official email', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Official phone', max_length=20)),
                ('effective_date', models.DateField(blank=True, help_text='Date division started', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('circle', models.ForeignKey(help_text='Parent Circle', on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='masters.circle')),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
                'db_table': 'masters_division',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='e.g., PMSGY', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full legal name of the program', max_length=500)),
                ('funding_agency', models.CharField(blank=True, help_text='Central Govt/State Govt/World Bank', max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget_head_code', models.CharField(blank=True, help_text='Budgetary ledger code', max_length=50)),
                ('objective', models.TextField(blank=True, help_text='Brief goal or purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme_type', models.ForeignKey(help_text='Scheme classification', on_delete=django.db.models.deletion.PROTECT, related_name='schemes', to='masters.schemetype')),
            ],
            options={
                'verbose_name': 'Scheme',
                'verbose_name_plural': 'Schemes',
                'db_table': 'masters_scheme',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SubDivision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='e.g., SD-01-W', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full name of Sub-Division', max_length=255)),
                ('jurisdiction_area', models.CharField(blank=True, help_text='Geographical area covered', max_length=500)),
                ('reporting_officer', models.CharField(blank=True, help_text='Sub-Divisional Engineer name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(help_text='Parent Division', on_delete=django.db.models.deletion.PROTECT, related_name='subdivisions', to='masters.division')),
            ],
            options={
                'verbose_name': 'Sub-Division',
                'verbose_name_plural': 'Sub-Divisions',
                'db_table': 'masters_subdivision',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='e.g., T-0010', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Official town/city name', max_length=255)),
                ('classification', models.CharField(choices=[('Metropolitan', 'Metropolitan'), ('Municipality', 'Municipality'), ('Town', 'Town'), ('Village', 'Village')], default='Town', max_length=20)),
                ('population', models.PositiveIntegerField(blank=True, help_text='Estimated population', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(help_text='Parent District', on_delete=django.db.models.deletion.PROTECT, related_name='towns', to='masters.district')),
            ],
            options={
                'verbose_name': 'Town/City',
                'verbose_name_plural': 'Towns/Cities',
                'db_table': 'masters_town',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='circle',
            name='zone',
            field=models.ForeignKey(help_text='Parent Zone', on_delete=django.db.models.deletion.PROTECT, related_name='circles', to='masters.zone'),
        ),
    ]
