# Generated by Django 6.0.1 on 2026-01-10 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_district_status_projectcategory_status_scheme_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Country name (e.g., India)', max_length=100, unique=True)),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2 code (e.g., IN)', max_length=3, unique=True)),
                ('dial_code', models.CharField(help_text='Country calling code (e.g., +91)', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this country is active in the system')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'masters_countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='State/Province name', max_length=100)),
                ('code', models.CharField(blank=True, help_text='State code (e.g., TG for Telangana)', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this state is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(help_text='Parent country', on_delete=django.db.models.deletion.CASCADE, related_name='states', to='masters.country')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'masters_states',
                'ordering': ['country', 'name'],
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='City name', max_length=100)),
                ('code', models.CharField(blank=True, help_text='City code if applicable', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this city is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(help_text='Parent state', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='masters.state')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'masters_cities',
                'ordering': ['state', 'name'],
                'unique_together': {('state', 'name')},
            },
        ),
    ]
