# Generated by Django 6.0 on 2025-12-24 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_workpackage'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundHead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.CharField(help_text='e.g. World Bank Loan, State Budget', max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_available', models.DecimalField(decimal_places=2, max_digits=15)),
                ('allocation_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_category', models.CharField(choices=[('MATERIAL', 'Material'), ('LABOUR', 'Labour'), ('MACHINERY', 'Machinery'), ('OVERHEAD', 'Overhead'), ('PROFESSIONAL', 'Professional Fees'), ('OTHER', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='scheduling.scheduletask')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_auto_retention', models.BooleanField(default=True, help_text='Auto-calculate 5% retention on bills')),
                ('default_retention_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='For 30-Day Budget Pulse', null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_settings', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='RABill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_no', models.CharField(max_length=50)),
                ('work_order_no', models.CharField(max_length=100)),
                ('bill_date', models.DateField()),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Amount before GST', max_digits=15)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Gross + GST', max_digits=15)),
                ('tds_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tds_section_type', models.CharField(choices=[('194C_IND', '194C - Individual/HUF'), ('194C_OTH', '194C - Others'), ('194J', '194J - Professional'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('labour_cess_percentage', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('labour_cess_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('retention_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('retention_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('mobilization_advance_recovery', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('material_advance_recovery', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('plant_machinery_recovery', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('other_deduction_remarks', models.CharField(blank=True, max_length=255)),
                ('net_payable', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_bills', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ra_bills', to='scheduling.scheduletask')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ra_bills', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='RetentionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_held', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_released', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('HELD', 'Held'), ('RELEASED', 'Released')], default='HELD', max_length=20)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retention_ledger', to='finance.rabill')),
            ],
        ),
        migrations.CreateModel(
            name='VariationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='finance.budgetlineitem')),
            ],
        ),
    ]
