# Generated by Django 6.0 on 2025-12-25 07:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundhead',
            old_name='source_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='fundhead',
            name='allocation_date',
        ),
        migrations.AddField(
            model_name='fundhead',
            name='allocating_authority',
            field=models.CharField(default='Government', help_text='e.g. Dept of Finance', max_length=255),
        ),
        migrations.AddField(
            model_name='fundhead',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundhead',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fundhead',
            name='balance_available',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
    ]
