# Generated by Django 6.0 on 2025-12-26 15:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_budgetlineitem_fund_head'),
        ('projects', '0002_workpackage'),
        ('scheduling', '0002_scheduletask_external_id_scheduletask_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retentionledger',
            name='remarks',
        ),
        migrations.CreateModel(
            name='BOQItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(help_text='e.g. 2.1.1', max_length=50)),
                ('description', models.TextField()),
                ('uom', models.CharField(help_text='Unit of Measurement', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Qty * Rate', max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FROZEN', 'Frozen (Immutable)')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_items', to='projects.project')),
            ],
            options={
                'ordering': ['item_code'],
                'unique_together': {('project', 'item_code')},
            },
        ),
        migrations.CreateModel(
            name='BOQMilestoneMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percentage_allocated', models.DecimalField(decimal_places=2, help_text='How much of this BOQ item is consumed by this milestone?', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boq_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_mappings', to='finance.boqitem')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_mappings', to='scheduling.scheduletask')),
            ],
            options={
                'unique_together': {('boq_item', 'milestone')},
            },
        ),
    ]
