# Generated by Django 6.0 on 2025-12-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_remove_retentionledger_remarks_boqitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabill',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Store override flags or extra sync data'),
        ),
    ]
