# Generated by Django 6.0 on 2026-01-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_approvalrequest_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabill',
            name='bill_pdf_file',
            field=models.FileField(blank=True, help_text='Generated PDF bill saved to media/projects/{project_id}/ra_bills/', null=True, upload_to='projects/ra_bills/'),
        ),
    ]
