# Generated by Django 6.0 on 2026-01-18 13:12

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_rabill_bill_pdf_file'),
        ('projects', '0007_add_risk_management_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressCalculationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('physical_progress', models.FloatField()),
                ('financial_progress', models.FloatField()),
                ('earned_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_boq_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_executed_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('boq_items_count', models.IntegerField()),
                ('verified_executions_count', models.IntegerField()),
                ('physical_progress_delta', models.FloatField(default=0.0)),
                ('financial_progress_delta', models.FloatField(default=0.0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='projects.project')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-calculated_at'],
                'get_latest_by': 'calculated_at',
            },
        ),
        migrations.CreateModel(
            name='BOQExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('executed_quantity', models.DecimalField(decimal_places=4, help_text='Quantity executed/achieved in this entry', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('execution_date', models.DateField(help_text='Date when this work was executed')),
                ('period_from', models.DateField(blank=True, help_text='Start of execution period', null=True)),
                ('period_to', models.DateField(blank=True, help_text='End of execution period', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Verification'), ('VERIFIED', 'Verified by Authority'), ('REJECTED', 'Rejected'), ('REVISED', 'Revision Required')], default='DRAFT', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Execution remarks or notes')),
                ('supporting_documents', models.JSONField(blank=True, default=list, help_text='List of EDMS document IDs as evidence')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boq_item', models.ForeignKey(help_text='Reference to the BOQ item being executed', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='finance.boqitem')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_boq_executions', to=settings.AUTH_USER_MODEL)),
                ('ra_bill', models.ForeignKey(blank=True, help_text='Linked RA Bill for payment tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boq_executions', to='finance.rabill')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_boq_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-execution_date', '-created_at'],
                'indexes': [models.Index(fields=['boq_item', 'execution_date'], name='finance_boq_boq_ite_fba94a_idx'), models.Index(fields=['status'], name='finance_boq_status_70ea80_idx')],
            },
        ),
    ]
