# Generated by Django 6.0 on 2026-01-18 18:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_add_boq_execution_and_progress_log'),
        ('projects', '0007_add_risk_management_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEVMHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField(help_text='Date of this snapshot')),
                ('bac', models.DecimalField(decimal_places=2, help_text='Budget At Completion', max_digits=15)),
                ('pv', models.DecimalField(decimal_places=2, help_text='Planned Value', max_digits=15)),
                ('ac', models.DecimalField(decimal_places=2, help_text='Actual Cost', max_digits=15)),
                ('ev', models.DecimalField(decimal_places=2, help_text='Earned Value', max_digits=15)),
                ('cv', models.DecimalField(decimal_places=2, help_text='Cost Variance (EV-AC)', max_digits=15)),
                ('sv', models.DecimalField(decimal_places=2, help_text='Schedule Variance (EV-PV)', max_digits=15)),
                ('cpi', models.FloatField(help_text='Cost Performance Index (EV/AC)')),
                ('spi', models.FloatField(help_text='Schedule Performance Index (EV/PV)')),
                ('eac', models.DecimalField(decimal_places=2, help_text='Estimate At Completion', max_digits=15)),
                ('etc', models.DecimalField(decimal_places=2, help_text='Estimate To Complete', max_digits=15)),
                ('vac', models.DecimalField(decimal_places=2, help_text='Variance At Completion', max_digits=15)),
                ('planned_percent', models.FloatField(help_text='Planned % complete at snapshot date')),
                ('actual_percent', models.FloatField(help_text='Actual % complete at snapshot date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evm_history', to='projects.project')),
            ],
            options={
                'ordering': ['snapshot_date'],
                'indexes': [models.Index(fields=['project', 'snapshot_date'], name='finance_pro_project_6ef5aa_idx')],
                'unique_together': {('project', 'snapshot_date')},
            },
        ),
    ]
