# Generated by Django 6.0 on 2026-02-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_add_project_evm_history'),
        ('scheduling', '0004_scheduletask_actual_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqitem',
            name='linked_tasks',
            field=models.ManyToManyField(blank=True, help_text='Schedule tasks this BOQ item contributes to. Enables BOQ-weighted progress calculation.', related_name='boq_items', to='scheduling.scheduletask'),
        ),
    ]
