# Generated by Django 6.0 on 2026-02-24 15:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_alter_scheduletask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletask',
            name='actual_end_date',
            field=models.DateField(blank=True, help_text='Actual end date (when work was physically completed)', null=True),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='actual_start_date',
            field=models.DateField(blank=True, help_text='Actual start date (when work physically started)', null=True),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='baseline_end_date',
            field=models.DateField(blank=True, help_text='Frozen baseline end date. Set by freeze_baseline action.', null=True),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='baseline_start_date',
            field=models.DateField(blank=True, help_text='Frozen baseline start date. Set by freeze_baseline action.', null=True),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='physical_progress_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='BOQ-weighted physical progress (0-100%). Computed from linked BOQ execution data.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
