# Generated by Django 6.0 on 2026-01-06 16:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0003_add_linked_user_to_contractor'),
        ('projects', '0003_add_master_foreignkeys'),
        ('scheduling', '0002_scheduletask_external_id_scheduletask_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('technical_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('financial_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('combined_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('TECHNICAL_EVAL', 'Technical Evaluation'), ('FINANCIAL_EVAL', 'Financial Evaluation'), ('QUALIFIED', 'Qualified'), ('DISQUALIFIED', 'Disqualified'), ('AWARDED', 'Awarded'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('evaluation_date', models.DateTimeField(blank=True, null=True)),
                ('technical_remarks', models.TextField(blank=True)),
                ('financial_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='masters.contractor')),
                ('evaluated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-combined_score', 'bid_amount'],
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tender_no', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('earnest_money_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tender_type', models.CharField(choices=[('OPEN', 'Open Tender'), ('LIMITED', 'Limited Tender'), ('SINGLE', 'Single Source'), ('E_TENDER', 'e-Tender (GeM/NICDC Portal)')], default='OPEN', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('BID_OPEN', 'Bid Opening'), ('EVALUATION', 'Under Evaluation'), ('AWARDED', 'Awarded'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('submission_deadline', models.DateTimeField(blank=True, null=True)),
                ('bid_opening_date', models.DateTimeField(blank=True, null=True)),
                ('nicdc_portal_ref', models.CharField(blank=True, help_text='Reference ID from NICDC Procurement Portal', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenders', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='projects.project')),
                ('schedule_task', models.ForeignKey(blank=True, help_text='Linked schedule milestone/task for workflow alignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='scheduling.scheduletask')),
                ('work_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='projects.workpackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_no', models.CharField(max_length=50, unique=True)),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('revised_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('performance_guarantee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('signing_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('revised_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SIGNED', 'Signed'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='masters.contractor')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='projects.project')),
                ('schedule_task', models.ForeignKey(blank=True, help_text='Linked milestone - payments tied to schedule progress', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='scheduling.scheduletask')),
                ('winning_bid', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_contract', to='procurement.bid')),
                ('tender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='procurement.tender')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='procurement.tender'),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('tender', 'bidder')},
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variation_no', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('variation_type', models.CharField(choices=[('SCOPE_CHANGE', 'Scope Change'), ('TIME_EXTENSION', 'Time Extension'), ('PRICE_ADJUSTMENT', 'Price Adjustment'), ('QUANTITY_VARIATION', 'Quantity Variation')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Cost impact (+/-)', max_digits=15)),
                ('time_impact_days', models.IntegerField(default=0, help_text='Schedule impact in days')),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IMPLEMENTED', 'Implemented')], default='PROPOSED', max_length=20)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_task', models.ForeignKey(blank=True, help_text='Schedule task affected by this variation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations', to='scheduling.scheduletask')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_variations', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='procurement.contract')),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_variations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('contract', 'variation_no')},
            },
        ),
    ]
