"""
Command to populate India location master data (Country -> State -> District -> City)
Includes ALL states, UTs, and ALL districts (~766 districts).
"""
from django.core.management.base import BaseCommand
from masters.models import Country, State, LocationDistrict, City
from django.db import transaction

class Command(BaseCommand):
    help = 'Populates India states, districts and cities'

    def handle(self, *args, **options):
        self.stdout.write('Populating India location data...')

        # Data Structure: State -> District -> [Cities]
        # Complete dataset with all 766 districts of India
        INDIA_DATA = {
            "Andaman and Nicobar Islands": {
                "Nicobar": ["Nicobar"],
                "North and Middle Andaman": ["Mayabunder"],
                "South Andaman": ["Port Blair"],
            },
            "Andhra Pradesh": {
                "Alluri Sitharama Raju": ["Paderu"],
                "Anakapalli": ["Anakapalli"],
                "Anantapur": ["Anantapur", "Dharmavaram", "Guntakal", "Hindupur"],
                "Annamayya": ["Rayachoti"],
                "Bapatla": ["Bapatla", "Chirala"],
                "Chittoor": ["Chittoor", "Palamaner"],
                "Dr. B.R. Ambedkar Konaseema": ["Amalapuram"],
                "East Godavari": ["Rajahmundry", "Nidadavole"],
                "Eluru": ["Eluru", "Jangareddigudem"],
                "Guntur": ["Guntur", "Tenali", "Mangalagiri"],
                "Kakinada": ["Kakinada", "Tuni"],
                "Krishna": ["Machilipatnam", "Gudivada"],
                "Kurnool": ["Kurnool", "Adoni"],
                "Nandyal": ["Nandyal", "Dhone"],
                "NTR": ["Vijayawada", "Nuzvid"],
                "Palnadu": ["Narasaraopet", "Sattenapalle"],
                "Parvathipuram Manyam": ["Parvathipuram"],
                "Prakasam": ["Ongole", "Markapur"],
                "Sri Potti Sriramulu Nellore": ["Nellore", "Kavali", "Gudur"],
                "Sri Sathya Sai": ["Puttaparthi", "Kadiri"],
                "Srikakulam": ["Srikakulam", "Palasa"],
                "Tirupati": ["Tirupati", "Srikalahasti"],
                "Visakhapatnam": ["Visakhapatnam", "Bheemunipatnam"],
                "Vizianagaram": ["Vizianagaram", "Bobbili"],
                "West Godavari": ["Bhimavaram", "Tanuku", "Tadepalligudem"],
                "YSR": ["Kadapa", "Proddatur", "Jammalamadugu"],
            },
            "Arunachal Pradesh": {
                "Anjaw": ["Hawai"],
                "Changlang": ["Changlang"],
                "Dibang Valley": ["Anini"],
                "East Kameng": ["Seppa"],
                "East Siang": ["Pasighat"],
                "Kamle": ["Raga"],
                "Kra Daadi": ["Jamin"],
                "Kurung Kumey": ["Koloriang"],
                "Lepa Rada": ["Basar"],
                "Lohit": ["Tezu"],
                "Longding": ["Longding"],
                "Lower Dibang Valley": ["Roing"],
                "Lower Siang": ["Likabali"],
                "Lower Subansiri": ["Ziro"],
                "Namsai": ["Namsai"],
                "Pakke Kessang": ["Lemmi"],
                "Papum Pare": ["Yupia", "Itanagar", "Naharlagun"],
                "Shi Yomi": ["Tato"],
                "Siang": ["Boleng"],
                "Tawang": ["Tawang"],
                "Tirap": ["Khonsa"],
                "Upper Siang": ["Yingkiong"],
                "Upper Subansiri": ["Daporijo"],
                "West Kameng": ["Bomdila"],
                "West Siang": ["Aalo"],
            },
            "Assam": {
                "Bajali": ["Pathsala"],
                "Baksa": ["Mushalpur"],
                "Barpeta": ["Barpeta"],
                "Biswanath": ["Biswanath Chariali"],
                "Bongaigaon": ["Bongaigaon"],
                "Cachar": ["Silchar"],
                "Charaideo": ["Sonari"],
                "Chirang": ["Kajalgaon"],
                "Darrang": ["Mangaldai"],
                "Dhemaji": ["Dhemaji"],
                "Dhubri": ["Dhubri"],
                "Dibrugarh": ["Dibrugarh"],
                "Dima Hasao": ["Haflong"],
                "Goalpara": ["Goalpara"],
                "Golaghat": ["Golaghat"],
                "Hailakandi": ["Hailakandi"],
                "Hojai": ["Hojai"],
                "Jorhat": ["Jorhat"],
                "Kamrup": ["Amingaon"],
                "Kamrup Metropolitan": ["Guwahati", "Dispur"],
                "Karbi Anglong": ["Diphu"],
                "Karimganj": ["Karimganj"],
                "Kokrajhar": ["Kokrajhar"],
                "Lakhimpur": ["North Lakhimpur"],
                "Majuli": ["Garamur"],
                "Morigaon": ["Morigaon"],
                "Nagaon": ["Nagaon"],
                "Nalbari": ["Nalbari"],
                "Sivasagar": ["Sivasagar"],
                "Sonitpur": ["Tezpur"],
                "South Salmara Mankachar": ["Hatsingimari"],
                "Tamulpur": ["Tamulpur"],
                "Tinsukia": ["Tinsukia"],
                "Udalguri": ["Udalguri"],
                "West Karbi Anglong": ["Hamren"],
            },
            "Bihar": {
                "Araria": ["Araria"],
                "Arwal": ["Arwal"],
                "Aurangabad": ["Aurangabad"],
                "Banka": ["Banka"],
                "Begusarai": ["Begusarai"],
                "Bhagalpur": ["Bhagalpur", "Sultanganj"],
                "Bhojpur": ["Arrah"],
                "Buxar": ["Buxar"],
                "Darbhanga": ["Darbhanga"],
                "East Champaran": ["Motihari"],
                "Gaya": ["Gaya", "Bodh Gaya"],
                "Gopalganj": ["Gopalganj"],
                "Jamui": ["Jamui"],
                "Jehanabad": ["Jehanabad"],
                "Kaimur": ["Bhabua"],
                "Katihar": ["Katihar"],
                "Khagaria": ["Khagaria"],
                "Kishanganj": ["Kishanganj"],
                "Lakhisarai": ["Lakhisarai"],
                "Madhepura": ["Madhepura"],
                "Madhubani": ["Madhubani"],
                "Munger": ["Munger"],
                "Muzaffarpur": ["Muzaffarpur"],
                "Nalanda": ["Bihar Sharif"],
                "Nawada": ["Nawada"],
                "Patna": ["Patna", "Danapur"],
                "Purnia": ["Purnia"],
                "Rohtas": ["Sasaram"],
                "Saharsa": ["Saharsa"],
                "Samastipur": ["Samastipur"],
                "Saran": ["Chhapra"],
                "Sheikhpura": ["Sheikhpura"],
                "Sheohar": ["Sheohar"],
                "Sitamarhi": ["Sitamarhi"],
                "Siwan": ["Siwan"],
                "Supaul": ["Supaul"],
                "Vaishali": ["Hajipur"],
                "West Champaran": ["Bettiah"],
            },
            "Chandigarh": {
                "Chandigarh": ["Chandigarh"],
            },
            "Chhattisgarh": {
                "Balod": ["Balod"],
                "Baloda Bazar": ["Baloda Bazar"],
                "Balrampur": ["Balrampur"],
                "Bastar": ["Jagdalpur"],
                "Bemetara": ["Bemetara"],
                "Bijapur": ["Bijapur"],
                "Bilaspur": ["Bilaspur"],
                "Dantewada": ["Dantewada"],
                "Dhamtari": ["Dhamtari"],
                "Durg": ["Durg", "Bhilai"],
                "Gariaband": ["Gariaband"],
                "Gaurela-Pendra-Marwahi": ["Gaurela"],
                "Janjgir-Champa": ["Janjgir"],
                "Jashpur": ["Jashpur Nagar"],
                "Kabirdham": ["Kawardha"],
                "Kanker": ["Kanker"],
                "Khairagarh-Chhuikhadan-Gandai": ["Khairagarh"],
                "Kondagaon": ["Kondagaon"],
                "Korba": ["Korba"],
                "Koriya": ["Baikunthpur"],
                "Mahasamund": ["Mahasamund"],
                "Manendragarh-Chirmiri-Bharatpur": ["Manendragarh"],
                "Mohla-Manpur-Ambagarh Chowki": ["Mohla"],
                "Mungeli": ["Mungeli"],
                "Narayanpur": ["Narayanpur"],
                "Raigarh": ["Raigarh"],
                "Raipur": ["Raipur"],
                "Rajnandgaon": ["Rajnandgaon"],
                "Sarangarh-Bilaigarh": ["Sarangarh"],
                "Shakti": ["Shakti"],
                "Sukma": ["Sukma"],
                "Surajpur": ["Surajpur"],
                "Surguja": ["Ambikapur"],
            },
            "Dadra and Nagar Haveli and Daman and Diu": {
                "Dadra and Nagar Haveli": ["Silvassa"],
                "Daman": ["Daman"],
                "Diu": ["Diu"],
            },
            "Delhi": {
                "Central Delhi": ["Daryaganj", "Karol Bagh"],
                "East Delhi": ["Preet Vihar", "Mayur Vihar"],
                "New Delhi": ["Connaught Place", "Chanakyapuri"],
                "North Delhi": ["Sadar Bazar", "Civil Lines"],
                "North East Delhi": ["Seelampur", "Shahdara"],
                "North West Delhi": ["Kanjhawala", "Rohini"],
                "Shahdara": ["Shahdara"],
                "South Delhi": ["Saket", "Hauz Khas"],
                "South East Delhi": ["Defence Colony", "Kalkaji"],
                "South West Delhi": ["Dwarka", "Vasant Kunj"],
                "West Delhi": ["Rajouri Garden", "Punjabi Bagh"],
            },
            "Goa": {
                "North Goa": ["Panaji", "Mapusa", "Bicholim"],
                "South Goa": ["Margao", "Vasco da Gama", "Ponda"],
            },
            "Gujarat": {
                "Ahmedabad": ["Ahmedabad", "Sanand", "Dholka"],
                "Amreli": ["Amreli"],
                "Anand": ["Anand"],
                "Aravalli": ["Modasa"],
                "Banaskantha": ["Palanpur"],
                "Bharuch": ["Bharuch", "Ankleshwar"],
                "Bhavnagar": ["Bhavnagar", "Palitana"],
                "Botad": ["Botad"],
                "Chhota Udaipur": ["Chhota Udaipur"],
                "Dahod": ["Dahod"],
                "Dang": ["Ahwa"],
                "Devbhoomi Dwarka": ["Khambhalia", "Dwarka"],
                "Gandhinagar": ["Gandhinagar"],
                "Gir Somnath": ["Veraval"],
                "Jamnagar": ["Jamnagar"],
                "Junagadh": ["Junagadh"],
                "Kheda": ["Nadiad"],
                "Kutch": ["Bhuj", "Gandhidham", "Anjar", "Mandvi"],
                "Mahisagar": ["Lunavada"],
                "Mehsana": ["Mehsana"],
                "Morbi": ["Morbi"],
                "Narmada": ["Rajpipla"],
                "Navsari": ["Navsari"],
                "Panchmahal": ["Godhra"],
                "Patan": ["Patan"],
                "Porbandar": ["Porbandar"],
                "Rajkot": ["Rajkot", "Gondal"],
                "Sabarkantha": ["Himmatnagar"],
                "Surat": ["Surat", "Bardoli"],
                "Surendranagar": ["Surendranagar"],
                "Tapi": ["Vyara"],
                "Vadodara": ["Vadodara"],
                "Valsad": ["Valsad", "Vapi"],
            },
            "Haryana": {
                "Ambala": ["Ambala", "Ambala Cantt"],
                "Bhiwani": ["Bhiwani"],
                "Charkhi Dadri": ["Charkhi Dadri"],
                "Faridabad": ["Faridabad"],
                "Fatehabad": ["Fatehabad"],
                "Gurugram": ["Gurugram", "Manesar", "Sohna"],
                "Hisar": ["Hisar", "Hansi"],
                "Jhajjar": ["Jhajjar", "Bahadurgarh"],
                "Jind": ["Jind"],
                "Kaithal": ["Kaithal"],
                "Karnal": ["Karnal"],
                "Kurukshetra": ["Kurukshetra", "Thanesar"],
                "Mahendragarh": ["Narnaul"],
                "Nuh": ["Nuh"],
                "Palwal": ["Palwal"],
                "Panchkula": ["Panchkula"],
                "Panipat": ["Panipat"],
                "Rewari": ["Rewari"],
                "Rohtak": ["Rohtak"],
                "Sirsa": ["Sirsa"],
                "Sonipat": ["Sonipat"],
                "Yamunanagar": ["Yamunanagar", "Jagadhri"],
            },
            "Himachal Pradesh": {
                "Bilaspur": ["Bilaspur"],
                "Chamba": ["Chamba", "Dalhousie"],
                "Hamirpur": ["Hamirpur"],
                "Kangra": ["Dharamshala", "Kangra", "Palampur"],
                "Kinnaur": ["Reckong Peo"],
                "Kullu": ["Kullu", "Manali"],
                "Lahaul and Spiti": ["Keylong"],
                "Mandi": ["Mandi", "Sundernagar"],
                "Shimla": ["Shimla", "Rampur"],
                "Sirmaur": ["Nahan", "Paonta Sahib"],
                "Solan": ["Solan", "Baddi"],
                "Una": ["Una"],
            },
            "Jammu and Kashmir": {
                "Anantnag": ["Anantnag", "Pahalgam"],
                "Bandipora": ["Bandipora"],
                "Baramulla": ["Baramulla", "Sopore", "Gulmarg"],
                "Budgam": ["Budgam"],
                "Doda": ["Doda"],
                "Ganderbal": ["Ganderbal"],
                "Jammu": ["Jammu", "Akhnoor"],
                "Kathua": ["Kathua"],
                "Kishtwar": ["Kishtwar"],
                "Kulgam": ["Kulgam"],
                "Kupwara": ["Kupwara"],
                "Poonch": ["Poonch"],
                "Pulwama": ["Pulwama"],
                "Rajouri": ["Rajouri"],
                "Ramban": ["Ramban"],
                "Reasi": ["Reasi", "Katra"],
                "Samba": ["Samba"],
                "Shopian": ["Shopian"],
                "Srinagar": ["Srinagar"],
                "Udhampur": ["Udhampur"],
            },
            "Jharkhand": {
                "Bokaro": ["Bokaro Steel City"],
                "Chatra": ["Chatra"],
                "Deoghar": ["Deoghar"],
                "Dhanbad": ["Dhanbad"],
                "Dumka": ["Dumka"],
                "East Singhbhum": ["Jamshedpur", "Ghatshila"],
                "Garhwa": ["Garhwa"],
                "Giridih": ["Giridih"],
                "Godda": ["Godda"],
                "Gumla": ["Gumla"],
                "Hazaribagh": ["Hazaribagh"],
                "Jamtara": ["Jamtara"],
                "Khunti": ["Khunti"],
                "Koderma": ["Koderma", "Jhumri Telaiya"],
                "Latehar": ["Latehar"],
                "Lohardaga": ["Lohardaga"],
                "Pakur": ["Pakur"],
                "Palamu": ["Daltonganj"],
                "Ramgarh": ["Ramgarh"],
                "Ranchi": ["Ranchi"],
                "Sahibganj": ["Sahibganj"],
                "Seraikela-Kharsawan": ["Seraikela", "Adityapur"],
                "Simdega": ["Simdega"],
                "West Singhbhum": ["Chaibasa"],
            },
            "Karnataka": {
                "Bagalkot": ["Bagalkot"],
                "Ballari": ["Ballari"],
                "Belagavi": ["Belagavi"],
                "Bengaluru Rural": ["Doddaballapura", "Devanahalli"],
                "Bengaluru Urban": ["Bengaluru"],
                "Bidar": ["Bidar"],
                "Chamarajanagar": ["Chamarajanagar"],
                "Chikkaballapura": ["Chikkaballapura"],
                "Chikkamagaluru": ["Chikkamagaluru"],
                "Chitradurga": ["Chitradurga"],
                "Dakshina Kannada": ["Mangaluru"],
                "Davanagere": ["Davanagere"],
                "Dharwad": ["Hubballi", "Dharwad"],
                "Gadag": ["Gadag-Betigeri"],
                "Hassan": ["Hassan"],
                "Haveri": ["Haveri"],
                "Kalaburagi": ["Kalaburagi"],
                "Kodagu": ["Madikeri"],
                "Kolar": ["Kolar"],
                "Koppal": ["Koppal"],
                "Mandya": ["Mandya"],
                "Mysuru": ["Mysuru"],
                "Raichur": ["Raichur"],
                "Ramanagara": ["Ramanagara"],
                "Shivamogga": ["Shivamogga"],
                "Tumakuru": ["Tumakuru"],
                "Udupi": ["Udupi"],
                "Uttara Kannada": ["Karwar", "Sirsi"],
                "Vijayanagara": ["Hosapete"],
                "Vijayapura": ["Vijayapura"],
                "Yadgir": ["Yadgir"],
            },
            "Kerala": {
                "Alappuzha": ["Alappuzha", "Kayamkulam"],
                "Ernakulam": ["Kochi", "Aluva", "Angamaly"],
                "Idukki": ["Painavu", "Thodupuzha"],
                "Kannur": ["Kannur", "Thalassery"],
                "Kasaragod": ["Kasaragod", "Kanhangad"],
                "Kollam": ["Kollam", "Punalur"],
                "Kottayam": ["Kottayam", "Changanassery"],
                "Kozhikode": ["Kozhikode", "Vadakara"],
                "Malappuram": ["Malappuram", "Manjeri"],
                "Palakkad": ["Palakkad"],
                "Pathanamthitta": ["Pathanamthitta", "Thiruvalla"],
                "Thiruvananthapuram": ["Thiruvananthapuram", "Neyyattinkara"],
                "Thrissur": ["Thrissur", "Guruvayur"],
                "Wayanad": ["Kalpetta"],
            },
            "Ladakh": {
                "Kargil": ["Kargil"],
                "Leh": ["Leh"],
            },
            "Lakshadweep": {
                "Lakshadweep": ["Kavaratti"],
            },
            "Madhya Pradesh": {
                "Agar Malwa": ["Agar"],
                "Alirajpur": ["Alirajpur"],
                "Anuppur": ["Anuppur"],
                "Ashoknagar": ["Ashoknagar"],
                "Balaghat": ["Balaghat"],
                "Barwani": ["Barwani"],
                "Betul": ["Betul"],
                "Bhind": ["Bhind"],
                "Bhopal": ["Bhopal"],
                "Burhanpur": ["Burhanpur"],
                "Chhatarpur": ["Chhatarpur"],
                "Chhindwara": ["Chhindwara"],
                "Damoh": ["Damoh"],
                "Datia": ["Datia"],
                "Dewas": ["Dewas"],
                "Dhar": ["Dhar"],
                "Dindori": ["Dindori"],
                "Guna": ["Guna"],
                "Gwalior": ["Gwalior"],
                "Harda": ["Harda"],
                "Indore": ["Indore", "Mhow"],
                "Jabalpur": ["Jabalpur"],
                "Jhabua": ["Jhabua"],
                "Katni": ["Katni"],
                "Khandwa": ["Khandwa"],
                "Khargone": ["Khargone"],
                "Maihar": ["Maihar"],
                "Mandla": ["Mandla"],
                "Mandsaur": ["Mandsaur"],
                "Mauganj": ["Mauganj"],
                "Morena": ["Morena"],
                "Narmadapuram": ["Itarsi", "Hoshangabad"],
                "Narsinghpur": ["Narsinghpur"],
                "Neemuch": ["Neemuch"],
                "Niwari": ["Niwari"],
                "Pandhurna": ["Pandhurna"],
                "Panna": ["Panna"],
                "Raisen": ["Raisen"],
                "Rajgarh": ["Rajgarh"],
                "Ratlam": ["Ratlam"],
                "Rewa": ["Rewa"],
                "Sagar": ["Sagar"],
                "Satna": ["Satna"],
                "Sehore": ["Sehore"],
                "Seoni": ["Seoni"],
                "Shahdol": ["Shahdol"],
                "Shajapur": ["Shajapur"],
                "Sheopur": ["Sheopur"],
                "Shivpuri": ["Shivpuri"],
                "Sidhi": ["Sidhi"],
                "Singrauli": ["Singrauli"],
                "Tikamgarh": ["Tikamgarh"],
                "Ujjain": ["Ujjain"],
                "Umaria": ["Umaria"],
                "Vidisha": ["Vidisha"],
            },
            "Maharashtra": {
                "Ahmednagar": ["Ahmednagar", "Sangamner"],
                "Akola": ["Akola"],
                "Amravati": ["Amravati"],
                "Aurangabad": ["Chhatrapati Sambhajinagar"],
                "Beed": ["Beed"],
                "Bhandara": ["Bhandara"],
                "Buldhana": ["Buldhana"],
                "Chandrapur": ["Chandrapur"],
                "Dhule": ["Dhule"],
                "Gadchiroli": ["Gadchiroli"],
                "Gondia": ["Gondia"],
                "Hingoli": ["Hingoli"],
                "Jalgaon": ["Jalgaon", "Bhusawal"],
                "Jalna": ["Jalna"],
                "Kolhapur": ["Kolhapur"],
                "Latur": ["Latur"],
                "Mumbai City": ["Mumbai"],
                "Mumbai Suburban": ["Bandra", "Andheri", "Borivali"],
                "Nagpur": ["Nagpur"],
                "Nanded": ["Nanded"],
                "Nandurbar": ["Nandurbar"],
                "Nashik": ["Nashik", "Malegaon"],
                "Osmanabad": ["Dharashiv"],
                "Palghar": ["Palghar", "Vasai-Virar"],
                "Parbhani": ["Parbhani"],
                "Pune": ["Pune", "Pimpri-Chinchwad"],
                "Raigad": ["Alibag", "Panvel"],
                "Ratnagiri": ["Ratnagiri"],
                "Sangli": ["Sangli", "Miraj"],
                "Satara": ["Satara"],
                "Sindhudurg": ["Oros", "Malvan"],
                "Solapur": ["Solapur"],
                "Thane": ["Thane", "Kalyan-Dombivli", "Ulhasnagar"],
                "Wardha": ["Wardha"],
                "Washim": ["Washim"],
                "Yavatmal": ["Yavatmal"],
            },
            "Manipur": {
                "Bishnupur": ["Bishnupur"],
                "Chandel": ["Chandel"],
                "Churachandpur": ["Churachandpur"],
                "Imphal East": ["Porompat"],
                "Imphal West": ["Imphal"],
                "Jiribam": ["Jiribam"],
                "Kakching": ["Kakching"],
                "Kamjong": ["Kamjong"],
                "Kangpokpi": ["Kangpokpi"],
                "Noney": ["Noney"],
                "Pherzawl": ["Pherzawl"],
                "Senapati": ["Senapati"],
                "Tamenglong": ["Tamenglong"],
                "Tengnoupal": ["Tengnoupal"],
                "Thoubal": ["Thoubal"],
                "Ukhrul": ["Ukhrul"],
            },
            "Meghalaya": {
                "East Garo Hills": ["Williamnagar"],
                "East Jaintia Hills": ["Khliehriat"],
                "East Khasi Hills": ["Shillong"],
                "Eastern West Khasi Hills": ["Mairang"],
                "North Garo Hills": ["Resubelpara"],
                "Ri Bhoi": ["Nongpoh"],
                "South Garo Hills": ["Baghmara"],
                "South West Garo Hills": ["Ampati"],
                "South West Khasi Hills": ["Mawkyrwat"],
                "West Garo Hills": ["Tura"],
                "West Jaintia Hills": ["Jowai"],
                "West Khasi Hills": ["Nongstoin"],
            },
            "Mizoram": {
                "Aizawl": ["Aizawl"],
                "Champhai": ["Champhai"],
                "Hnahthial": ["Hnahthial"],
                "Khawzawl": ["Khawzawl"],
                "Kolasib": ["Kolasib"],
                "Lawngtlai": ["Lawngtlai"],
                "Lunglei": ["Lunglei"],
                "Mamit": ["Mamit"],
                "Saiha": ["Saiha"],
                "Saitual": ["Saitual"],
                "Serchhip": ["Serchhip"],
            },
            "Nagaland": {
                "Chumoukedima": ["Chumoukedima"],
                "Dimapur": ["Dimapur"],
                "Kiphire": ["Kiphire"],
                "Kohima": ["Kohima"],
                "Longleng": ["Longleng"],
                "Mokokchung": ["Mokokchung"],
                "Mon": ["Mon"],
                "Niuland": ["Niuland"],
                "Noklak": ["Noklak"],
                "Peren": ["Peren"],
                "Phek": ["Phek"],
                "Shamator": ["Shamator"],
                "Tseminyu": ["Tseminyu"],
                "Tuensang": ["Tuensang"],
                "Wokha": ["Wokha"],
                "Zunheboto": ["Zunheboto"],
            },
            "Odisha": {
                "Angul": ["Angul"],
                "Balangir": ["Balangir"],
                "Balasore": ["Balasore"],
                "Bargarh": ["Bargarh"],
                "Bhadrak": ["Bhadrak"],
                "Boudh": ["Boudh"],
                "Cuttack": ["Cuttack"],
                "Deogarh": ["Deogarh"],
                "Dhenkanal": ["Dhenkanal"],
                "Gajapati": ["Paralakhemundi"],
                "Ganjam": ["Chhatrapur", "Berhampur"],
                "Jagatsinghpur": ["Jagatsinghpur"],
                "Jajpur": ["Jajpur"],
                "Jharsuguda": ["Jharsuguda"],
                "Kalahandi": ["Bhawanipatna"],
                "Kandhamal": ["Phulbani"],
                "Kendrapara": ["Kendrapara"],
                "Kendujhar": ["Kendujhar"],
                "Khordha": ["Bhubaneswar", "Khordha"],
                "Koraput": ["Koraput", "Jeypore"],
                "Malkangiri": ["Malkangiri"],
                "Mayurbhanj": ["Baripada"],
                "Nabarangpur": ["Nabarangpur"],
                "Nayagarh": ["Nayagarh"],
                "Nuapada": ["Nuapada"],
                "Puri": ["Puri"],
                "Rayagada": ["Rayagada"],
                "Sambalpur": ["Sambalpur"],
                "Subarnapur": ["Sonepur"],
                "Sundargarh": ["Sundargarh", "Rourkela"],
            },
            "Puducherry": {
                "Karaikal": ["Karaikal"],
                "Mahe": ["Mahe"],
                "Puducherry": ["Puducherry"],
                "Yanam": ["Yanam"],
            },
            "Punjab": {
                "Amritsar": ["Amritsar"],
                "Barnala": ["Barnala"],
                "Bathinda": ["Bathinda"],
                "Faridkot": ["Faridkot"],
                "Fatehgarh Sahib": ["Sirhind"],
                "Fazilka": ["Fazilka", "Abohar"],
                "Ferozepur": ["Ferozepur"],
                "Gurdaspur": ["Gurdaspur", "Batala"],
                "Hoshiarpur": ["Hoshiarpur"],
                "Jalandhar": ["Jalandhar"],
                "Kapurthala": ["Kapurthala"],
                "Ludhiana": ["Ludhiana", "Jagraon", "Khanna"],
                "Malerkotla": ["Malerkotla"],
                "Mansa": ["Mansa"],
                "Moga": ["Moga"],
                "Muktsar": ["Muktsar"],
                "Pathankot": ["Pathankot"],
                "Patiala": ["Patiala", "Rajpura"],
                "Rupnagar": ["Rupnagar"],
                "SAS Nagar": ["Mohali", "Zirakpur", "Kharar"],
                "Sangrur": ["Sangrur"],
                "Shaheed Bhagat Singh Nagar": ["Nawanshahr"],
                "Tarn Taran": ["Tarn Taran"],
            },
            "Rajasthan": {
                "Ajmer": ["Ajmer", "Kishangarh"],
                "Alwar": ["Alwar", "Bhiwadi"],
                "Anupgarh": ["Anupgarh"],
                "Balotra": ["Balotra"],
                "Banswara": ["Banswara"],
                "Baran": ["Baran"],
                "Barmer": ["Barmer"],
                "Beawar": ["Beawar"],
                "Bharatpur": ["Bharatpur"],
                "Bhilwara": ["Bhilwara"],
                "Bikaner": ["Bikaner"],
                "Bundi": ["Bundi"],
                "Chittorgarh": ["Chittorgarh"],
                "Churu": ["Churu"],
                "Dausa": ["Dausa"],
                "Deeg": ["Deeg"],
                "Dholpur": ["Dholpur"],
                "Didwana-Kuchaman": ["Didwana"],
                "Dudu": ["Dudu"],
                "Dungarpur": ["Dungarpur"],
                "Gangapur City": ["Gangapur"],
                "Hanumangarh": ["Hanumangarh"],
                "Jaipur": ["Jaipur"],
                "Jaipur Rural": ["Bagru"],
                "Jaisalmer": ["Jaisalmer"],
                "Jalore": ["Jalore"],
                "Jhalawar": ["Jhalawar"],
                "Jhunjhunu": ["Jhunjhunu"],
                "Jodhpur": ["Jodhpur"],
                "Jodhpur Rural": ["Luni"],
                "Karauli": ["Karauli"],
                "Kekri": ["Kekri"],
                "Khairthal-Tijara": ["Tijara"],
                "Kota": ["Kota"],
                "Kotputli-Behror": ["Kotputli"],
                "Nagaur": ["Nagaur"],
                "Neem Ka Thana": ["Neem Ka Thana"],
                "Pali": ["Pali"],
                "Phalodi": ["Phalodi"],
                "Pratapgarh": ["Pratapgarh"],
                "Rajsamand": ["Rajsamand"],
                "Salumbar": ["Salumbar"],
                "Sanchore": ["Sanchore"],
                "Sawai Madhopur": ["Sawai Madhopur"],
                "Shahpura": ["Shahpura"],
                "Sikar": ["Sikar"],
                "Sirohi": ["Sirohi", "Mount Abu"],
                "Sri Ganganagar": ["Sri Ganganagar"],
                "Tonk": ["Tonk"],
                "Udaipur": ["Udaipur"],
            },
            "Sikkim": {
                "Gangtok": ["Gangtok"],
                "Gyalshing": ["Gyalshing"],
                "Mangan": ["Mangan"],
                "Namchi": ["Namchi"],
                "Pakyong": ["Pakyong"],
                "Soreng": ["Soreng"],
            },
            "Tamil Nadu": {
                "Ariyalur": ["Ariyalur"],
                "Chengalpattu": ["Chengalpattu"],
                "Chennai": ["Chennai"],
                "Coimbatore": ["Coimbatore"],
                "Cuddalore": ["Cuddalore"],
                "Dharmapuri": ["Dharmapuri"],
                "Dindigul": ["Dindigul"],
                "Erode": ["Erode"],
                "Kallakurichi": ["Kallakurichi"],
                "Kancheepuram": ["Kancheepuram"],
                "Kanyakumari": ["Nagercoil"],
                "Karur": ["Karur"],
                "Krishnagiri": ["Krishnagiri", "Hosur"],
                "Madurai": ["Madurai"],
                "Mayiladuthurai": ["Mayiladuthurai"],
                "Nagapattinam": ["Nagapattinam"],
                "Namakkal": ["Namakkal"],
                "Nilgiris": ["Udhagamandalam", "Coonoor"],
                "Perambalur": ["Perambalur"],
                "Pudukkottai": ["Pudukkottai"],
                "Ramanathapuram": ["Ramanathapuram"],
                "Ranipet": ["Ranipet"],
                "Salem": ["Salem"],
                "Sivaganga": ["Sivaganga"],
                "Tenkasi": ["Tenkasi"],
                "Thanjavur": ["Thanjavur", "Kumbakonam"],
                "Theni": ["Theni"],
                "Thoothukudi": ["Thoothukudi"],
                "Tiruchirappalli": ["Tiruchirappalli"],
                "Tirunelveli": ["Tirunelveli"],
                "Tirupathur": ["Tirupathur"],
                "Tiruppur": ["Tiruppur"],
                "Tiruvallur": ["Tiruvallur"],
                "Tiruvannamalai": ["Tiruvannamalai"],
                "Tiruvarur": ["Tiruvarur"],
                "Vellore": ["Vellore"],
                "Viluppuram": ["Viluppuram"],
                "Virudhunagar": ["Virudhunagar"],
            },
            "Telangana": {
                "Adilabad": ["Adilabad"],
                "Bhadradri Kothagudem": ["Kothagudem"],
                "Hanamkonda": ["Hanamkonda"],
                "Hyderabad": ["Hyderabad", "Secunderabad"],
                "Jagtial": ["Jagtial"],
                "Jangaon": ["Jangaon"],
                "Jayashankar Bhupalpally": ["Bhupalpally"],
                "Jogulamba Gadwal": ["Gadwal"],
                "Kamareddy": ["Kamareddy"],
                "Karimnagar": ["Karimnagar"],
                "Khammam": ["Khammam"],
                "Komaram Bheem Asifabad": ["Asifabad"],
                "Mahabubabad": ["Mahabubabad"],
                "Mahbubnagar": ["Mahbubnagar"],
                "Mancherial": ["Mancherial"],
                "Medak": ["Medak"],
                "Medchal-Malkajgiri": ["Malkajgiri", "Kukatpally"],
                "Mulugu": ["Mulugu"],
                "Nagarkurnool": ["Nagarkurnool"],
                "Nalgonda": ["Nalgonda"],
                "Narayanpet": ["Narayanpet"],
                "Nirmal": ["Nirmal"],
                "Nizamabad": ["Nizamabad"],
                "Peddapalli": ["Peddapalli", "Ramagundam"],
                "Rajanna Sircilla": ["Sircilla"],
                "Rangareddy": ["L.B. Nagar", "Shamshabad"],
                "Sangareddy": ["Sangareddy"],
                "Siddipet": ["Siddipet"],
                "Suryapet": ["Suryapet"],
                "Vikarabad": ["Vikarabad"],
                "Wanaparthy": ["Wanaparthy"],
                "Warangal": ["Warangal"],
                "Yadadri Bhuvanagiri": ["Bhongir"],
            },
            "Tripura": {
                "Dhalai": ["Ambassa"],
                "Gomati": ["Udaipur"],
                "Khowai": ["Khowai"],
                "North Tripura": ["Dharmanagar"],
                "Sepahijala": ["Bishramganj"],
                "South Tripura": ["Belonia"],
                "Unakoti": ["Kailashahar"],
                "West Tripura": ["Agartala"],
            },
            "Uttar Pradesh": {
                "Agra": ["Agra"],
                "Aligarh": ["Aligarh"],
                "Ambedkar Nagar": ["Akbarpur"],
                "Amethi": ["Gauriganj"],
                "Amroha": ["Amroha"],
                "Auraiya": ["Auraiya"],
                "Ayodhya": ["Ayodhya", "Faizabad"],
                "Azamgarh": ["Azamgarh"],
                "Baghpat": ["Baghpat"],
                "Bahraich": ["Bahraich"],
                "Ballia": ["Ballia"],
                "Balrampur": ["Balrampur"],
                "Banda": ["Banda"],
                "Barabanki": ["Barabanki"],
                "Bareilly": ["Bareilly"],
                "Basti": ["Basti"],
                "Bhadohi": ["Gyanpur"],
                "Bijnor": ["Bijnor"],
                "Budaun": ["Budaun"],
                "Bulandshahr": ["Bulandshahr"],
                "Chandauli": ["Chandauli"],
                "Chitrakoot": ["Karwi"],
                "Deoria": ["Deoria"],
                "Etah": ["Etah"],
                "Etawah": ["Etawah"],
                "Farrukhabad": ["Fatehgarh"],
                "Fatehpur": ["Fatehpur"],
                "Firozabad": ["Firozabad"],
                "Gautam Buddha Nagar": ["Noida", "Greater Noida"],
                "Ghaziabad": ["Ghaziabad", "Loni"],
                "Ghazipur": ["Ghazipur"],
                "Gonda": ["Gonda"],
                "Gorakhpur": ["Gorakhpur"],
                "Hamirpur": ["Hamirpur"],
                "Hapur": ["Hapur"],
                "Hardoi": ["Hardoi"],
                "Hathras": ["Hathras"],
                "Jalaun": ["Orai"],
                "Jaunpur": ["Jaunpur"],
                "Jhansi": ["Jhansi"],
                "Kannauj": ["Kannauj"],
                "Kanpur Dehat": ["Akbarpur"],
                "Kanpur Nagar": ["Kanpur"],
                "Kasganj": ["Kasganj"],
                "Kaushambi": ["Manjhanpur"],
                "Kushinagar": ["Padrauna"],
                "Lakhimpur Kheri": ["Lakhimpur"],
                "Lalitpur": ["Lalitpur"],
                "Lucknow": ["Lucknow"],
                "Maharajganj": ["Maharajganj"],
                "Mahoba": ["Mahoba"],
                "Mainpuri": ["Mainpuri"],
                "Mathura": ["Mathura"],
                "Mau": ["Mau"],
                "Meerut": ["Meerut"],
                "Mirzapur": ["Mirzapur"],
                "Moradabad": ["Moradabad"],
                "Muzaffarnagar": ["Muzaffarnagar"],
                "Pilibhit": ["Pilibhit"],
                "Pratapgarh": ["Pratapgarh"],
                "Prayagraj": ["Prayagraj"],
                "Raebareli": ["Raebareli"],
                "Rampur": ["Rampur"],
                "Saharanpur": ["Saharanpur"],
                "Sambhal": ["Sambhal"],
                "Sant Kabir Nagar": ["Khalilabad"],
                "Shahjahanpur": ["Shahjahanpur"],
                "Shamli": ["Shamli"],
                "Shravasti": ["Bhinga"],
                "Siddharthnagar": ["Naugarh"],
                "Sitapur": ["Sitapur"],
                "Sonbhadra": ["Robertsganj"],
                "Sultanpur": ["Sultanpur"],
                "Unnao": ["Unnao"],
                "Varanasi": ["Varanasi"],
            },
            "Uttarakhand": {
                "Almora": ["Almora"],
                "Bageshwar": ["Bageshwar"],
                "Chamoli": ["Gopeshwar"],
                "Champawat": ["Champawat"],
                "Dehradun": ["Dehradun", "Rishikesh"],
                "Haridwar": ["Haridwar", "Roorkee"],
                "Nainital": ["Nainital", "Haldwani"],
                "Pauri Garhwal": ["Pauri"],
                "Pithoragarh": ["Pithoragarh"],
                "Rudraprayag": ["Rudraprayag"],
                "Tehri Garhwal": ["New Tehri"],
                "Udham Singh Nagar": ["Rudrapur"],
                "Uttarkashi": ["Uttarkashi"],
            },
            "West Bengal": {
                "Alipurduar": ["Alipurduar"],
                "Bankura": ["Bankura"],
                "Birbhum": ["Suri"],
                "Cooch Behar": ["Cooch Behar"],
                "Dakshin Dinajpur": ["Balurghat"],
                "Darjeeling": ["Darjeeling", "Siliguri"],
                "Hooghly": ["Chinsurah"],
                "Howrah": ["Howrah"],
                "Jalpaiguri": ["Jalpaiguri"],
                "Jhargram": ["Jhargram"],
                "Kalimpong": ["Kalimpong"],
                "Kolkata": ["Kolkata"],
                "Malda": ["English Bazar"],
                "Murshidabad": ["Berhampore"],
                "Nadia": ["Krishnanagar"],
                "North 24 Parganas": ["Barasat"],
                "Paschim Bardhaman": ["Asansol", "Durgapur"],
                "Paschim Medinipur": ["Medinipur"],
                "Purba Bardhaman": ["Bardhaman"],
                "Purba Medinipur": ["Tamluk"],
                "Purulia": ["Purulia"],
                "South 24 Parganas": ["Alipore"],
                "Uttar Dinajpur": ["Raiganj"],
            },
        }

        with transaction.atomic():
            # Create India
            india, _ = Country.objects.get_or_create(
                name='India',
                defaults={'code': 'IN', 'dial_code': '+91'}
            )
            self.stdout.write(f'Using Country: {india.name}')

            for state_name, districts_data in INDIA_DATA.items():
                # Create State
                state_code = state_name[:2].upper() # Naive code gen, can be improved
                state, _ = State.objects.get_or_create(
                    country=india,
                    name=state_name,
                    defaults={'code': state_code}
                )
                
                for district_name, cities_list in districts_data.items():
                     # Create District
                    district, _ = LocationDistrict.objects.get_or_create(
                        state=state,
                        name=district_name,
                        defaults={'code': district_name[:3].upper()}
                    )
                    
                    # Create Cities
                    for city_name in cities_list:
                        City.objects.get_or_create(
                            district=district,
                            name=city_name,
                            defaults={'code': city_name[:3].upper()}
                        )
                        
            self.stdout.write(self.style.SUCCESS(f'Successfully populated India locations!'))
            self.stdout.write(f'States: {State.objects.count()}')
            self.stdout.write(f'Districts: {LocationDistrict.objects.count()}')
            self.stdout.write(f'Cities: {City.objects.count()}')
