# Generated by Django 6.0 on 2026-01-18 19:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(help_text='Step order (1, 2, 3...)', validators=[django.core.validators.MinValueValidator(1)])),
                ('role', models.CharField(choices=[('SPV_Official', 'SPV Official'), ('PMNC_Team', 'PMNC Team'), ('EPC_Contractor', 'EPC Contractor'), ('Consultant_Design', 'Design Consultant'), ('Govt_Department', 'Government Department'), ('NICDC_HQ', 'NICDC HQ'), ('AE', 'Assistant Engineer'), ('EE', 'Executive Engineer'), ('SE', 'Superintending Engineer'), ('CE', 'Chief Engineer'), ('HOD', 'Head of Department'), ('DGM', 'Deputy General Manager'), ('GM', 'General Manager'), ('MD', 'Managing Director')], help_text='Role responsible for this step (e.g., AE, EE, SE, CE)', max_length=50)),
                ('action_type', models.CharField(choices=[('VERIFY', 'Verify & Check'), ('RECOMMEND', 'Recommend'), ('APPROVE', 'Approve'), ('SANCTION', 'Sanction'), ('REVIEW', 'Review')], max_length=20)),
                ('action_label', models.CharField(blank=True, help_text='Custom label like "Measure & Verify" or "Technical Sanction"', max_length=100)),
                ('can_revert', models.BooleanField(default=True, help_text='Allow reverting to previous step for clarification')),
                ('deadline_days', models.PositiveIntegerField(default=3, help_text='SLA in working days')),
                ('remarks_required', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Workflow Step',
                'verbose_name_plural': 'Workflow Steps',
                'ordering': ['template', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='DelegationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('module', models.CharField(blank=True, choices=[('RA_BILL', 'RA Bill'), ('TENDER', 'Tender'), ('DESIGN', 'Design Document'), ('VARIATION', 'Variation Order'), ('CONTRACT', 'Contract'), ('BOQ', 'BOQ Item'), ('RISK', 'Risk')], help_text='Leave empty to delegate all modules', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delegate_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL)),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delegation Rule',
                'verbose_name_plural': 'Delegation Rules',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(help_text='Model name (e.g., "RABill", "Tender")', max_length=50)),
                ('entity_id', models.UUIDField(help_text='Primary key of the document')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('REVERTED', 'Reverted for Clarification'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workflows', to=settings.AUTH_USER_MODEL)),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_initiated', to=settings.AUTH_USER_MODEL)),
                ('current_step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_instances', to='workflow.workflowstep')),
            ],
            options={
                'verbose_name': 'Workflow Instance',
                'verbose_name_plural': 'Workflow Instances',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('STARTED', 'Workflow Started'), ('FORWARD', 'Forwarded to Next Step'), ('REVERT', 'Reverted to Previous Step'), ('REJECT', 'Rejected'), ('COMPLETE', 'Workflow Completed'), ('DELEGATE', 'Delegated'), ('ESCALATE', 'Escalated')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_hours', models.FloatField(blank=True, null=True)),
                ('from_step', models.PositiveIntegerField(blank=True, null=True)),
                ('to_step', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_actions', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='workflow.workflowinstance')),
                ('step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='workflow.workflowstep')),
            ],
            options={
                'verbose_name': 'Workflow Audit Log',
                'verbose_name_plural': 'Workflow Audit Logs',
                'ordering': ['-entered_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('module', models.CharField(choices=[('RA_BILL', 'RA Bill'), ('TENDER', 'Tender'), ('DESIGN', 'Design Document'), ('VARIATION', 'Variation Order'), ('CONTRACT', 'Contract'), ('BOQ', 'BOQ Item'), ('RISK', 'Risk')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Use as fallback if no trigger rules match')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow Template',
                'verbose_name_plural': 'Workflow Templates',
                'ordering': ['module', 'name'],
            },
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflow.workflowtemplate'),
        ),
        migrations.CreateModel(
            name='WorkflowTriggerRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('module', models.CharField(choices=[('RA_BILL', 'RA Bill'), ('TENDER', 'Tender'), ('DESIGN', 'Design Document'), ('VARIATION', 'Variation Order'), ('CONTRACT', 'Contract'), ('BOQ', 'BOQ Item'), ('RISK', 'Risk')], max_length=20)),
                ('condition_field', models.CharField(help_text='Field to evaluate (e.g., "amount", "type", "project.category")', max_length=100)),
                ('condition_operator', models.CharField(choices=[('GT', 'Greater Than'), ('GTE', 'Greater Than or Equal'), ('LT', 'Less Than'), ('LTE', 'Less Than or Equal'), ('EQ', 'Equals'), ('NEQ', 'Not Equals'), ('IN', 'In List'), ('NOT_IN', 'Not In List'), ('CONTAINS', 'Contains')], max_length=20)),
                ('condition_value', models.CharField(help_text='Value to compare against (use comma-separated for IN/NOT_IN)', max_length=500)),
                ('logic_criteria', models.JSONField(blank=True, help_text='Advanced JSON logic for complex conditions', null=True)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower priority = evaluated first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_rules', to='workflow.workflowtemplate')),
            ],
            options={
                'verbose_name': 'Workflow Trigger Rule',
                'verbose_name_plural': 'Workflow Trigger Rules',
                'ordering': ['module', 'priority'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('template', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['entity_type', 'entity_id'], name='workflow_wo_entity__ad8afd_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['status'], name='workflow_wo_status_665f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['current_step'], name='workflow_wo_current_8115ad_idx'),
        ),
    ]
