# Generated by Django 6.0.1 on 2026-01-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_registration_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SPV_Official', 'SPV Official'), ('PMNC_Team', 'PMNC Team'), ('EPC_Contractor', 'EPC Contractor'), ('Consultant_Design', 'Design Consultant'), ('Govt_Department', 'Government Department'), ('NICDC_HQ', 'NICDC HQ'), ('AE', 'Assistant Engineer'), ('EE', 'Executive Engineer'), ('SE', 'Superintending Engineer'), ('CE', 'Chief Engineer'), ('DA', 'Divisional Accountant'), ('PD', 'Project Director')], default='SPV_Official', help_text='Designates the functional role of the user.', max_length=50),
        ),
    ]
